### ISSUE TITLE
How to prevent some classes from showing up as specifications in the report

### ISSUE THREAD

**Issue by nlazouzi** [renatoathaydes/spock-reports#101]
Basically, some of the classes in our project are used to prep for the actual tests. so it would be good if there was a way to make the reporter ignore them.
Is this possible ?

**Comment by renatoathaydes** [comment]
Do you actually run them as tests? Or you want them to not even run as tests?

If they run as tests, then the reports are created automatically and there's nothing you can do about that, currently.

This could be a new feature, though, if there's a good reason for it.

**Comment by nlazouzi** [comment]
No these are base classes that do some of the prep work before the tests are ran.  So my actual test classes extend these. So they show in the report with 0 features. I would prefer that they don't show up at all.
perhaps an annotation to make the report ignore them.
Thanks for the quick response.

**Comment by renatoathaydes** [comment]
I use Groovy `trait` for this kind of thing. Each trait provides a capability for the test.

For example, we have a http-client trait that, roughly, looks like this:

```groovy
trait CanTalkHttp {

    HttpResponse postJson(String endpoint, Map headers, String body) {
        // impl
    }

    // ... more methods

}
```

Then, a test might look like this:

```groovy
class MySpec extends Specification implements CanTalkHttp {
    def "Posts something"() {
        when: 'we post json'
        def response = postJson('/my-endpoint', [Accept: 'application/json'], '{"hi": true}')

        then: 'all is good'
        response.statusCode == 200
    }
}
```

If you make your base class extends `Specification`, then Spock will think it's a test... there's no reason to do that, though, as you can use traits as shown above (a class can implement any number of traits).

**Comment by nlazouzi** [comment]
we'll look into using traits.
Thank you
