### ISSUE TITLE
Generating a json file containing report parameters

### ISSUE THREAD

**Issue by krag451** [renatoathaydes/spock-reports#102]
First, thanks for creating this report extension.  I think it will helpful in generating the report format we need.

I wanted to generate a single json file containing both the summary and individual test case information.  I started to create a new template which does this though I keep running into issues with parameters I am adding to the template file.  I wanted to be able to debug the template in IDEA but I'm unsure how to do this.  When you are generating a new template file for the first time how do you typically debug it?

Thanks for any tips you can provide.

**Comment by renatoathaydes** [comment]
It is possible to debug code you call from templates in Java/Groovy files... but the code within your template cannot be debugged, unfortunately... so my current approach is to log information from the templates to confirm my believes, basically... good old logging where you can't debug.

Works well for me.... you just need to enable logging as explained [here](https://github.com/renatoathaydes/spock-reports/#customizing-spock-reports-logging).

To mix summary and feature reports might be a little tricky... as they were designed to be separated. But should be possible.

You might benefit from knowing that the summary data is already stored in a json file in the `spock-reports` directory called `aggregated_report.json`.

**Comment by krag451** [comment]
Thanks for the info.  I was able to figure out my issues with the template.  I was referencing a variable that was null.  Once I removed that I was able to create the report.

You mentioned that mixing the summary and feature might be tricky.  Where do you see the issue?  Are there feature methods/properties that are available to be used from a summary report?

**Comment by renatoathaydes** [comment]
The data available for the summary report is, unsurprisingly, a summary of the features that ran... it does not have information about each block/iteration of each spec, like the feature reports do. So, putting the two together will require you to store data somewhere between the two.
