### ISSUE TITLE
Clearing / Deleting old spock reports before each run

### ISSUE THREAD

**Issue by nartz** [renatoathaydes/spock-reports#105]
Hi - 

Is there an easy way to delete all old reports before each run (i.e. everything in the spock-reports folder)? If spec names change, etc, the old reports just end up sitting in the folder. Otherwise, I guess i can manually do it in test setup.

Thanks.

**Comment by renatoathaydes** [comment]
You can choose in which directory you want the reports to be located. The build system you use should be able to easily remove that directory before running tests.

For example , with Gradle, try this:

```groovy
tasks.test.doFirst {
    println "Deleting test reports: ${new File(project.buildDir, 'spock-reports')}"
    delete new File(project.buildDir, 'spock-reports')
}
```

In Maven, configure the maven-clean plugin accordingly.

**Comment by nartz** [comment]
Okay great - thanks.
