### ISSUE TITLE
Attaching Git Log

### ISSUE THREAD

**Issue by nartz** [renatoathaydes/spock-reports#106]
Our goal is to enhance the summary screen with a list of commits that were added (and their descriptions) (i.e. diff with master) on the Summary Template Screen. 

Whats the best way to incorporate these into the HTML template? Should we just fork the project and start editing the HTML generator code, or is there an easier way to put arbitrary text into the html templates?

Thanks.

**Comment by rdmueller** [comment]
If you use the template reports, you can script this feature with groovy inside the reports:
https://github.com/renatoathaydes/spock-reports#using-template-reports

That would work quite well :-)

**Comment by renatoathaydes** [comment]
I would just write a template report for that.

First, get a template that writes a HTML report. Someone wrote one, [see here](https://github.com/renatoathaydes/spock-reports/issues/77).

Then, modify the code within the template to get the data you need.

**Comment by nartz** [comment]
Okay great, thank you.
