### ISSUE TITLE
Adding spock-reports through a gradle plugin. An intersting issue !!!

### ISSUE THREAD

**Issue by nlazouzi** [renatoathaydes/spock-reports#108]
So i created a gradle plugin that adds the spock-reports extension to my project. I used system properties to overwrite the project name and version so that they can be included in the report. I did this because i have several projects where i need the reports generated.

After applying the plugin to my project and running my acceptanceTest task, i run into this issue only if all my tests pass 

Has anyone run into this before ??? Just wondering.

> >FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not add entry ':always-on-ats:acceptanceTest' to cache taskArtifacts.bin (/home/..projectDir/.gradle/2.9/taskArtifacts/taskArtifacts.bin).
> > Unable to store task input properties. Property 'systemProperties' with value '{com.athaydes.spockframework.report.projectName=always-on-ats, com.athaydes.spockframework.report.projectVersion=7.3.0.0, config.file=/home..projectDir/src/test/resources/local.conf}' cannot be serialized.'
> 

This is what my plugin looks like >>

```
package com
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.Task
import org.gradle.api.tasks.testing.Test

class SpockReportsPlugin implements Plugin<Project> {
   
 @Override
    void `apply(Project` project) {
        project.dependencies {
            testRuntime( 'com.athaydes:spock-reports:1.3.0' ) {
                transitive = false // this avoids affecting your version of Groovy/Spock
            }
        }

        project.afterEvaluate {
            project.tasks.forEach { Task task ->
                if (task instanceof Test) {

                        task.systemProperty "com.athaydes.spockframework.report.projectName", "${project.getName()}"
                        task.systemProperty "com.athaydes.spockframework.report.projectVersion", "${project.getVersion()}"
                    
                }
            }

        }

    }
}
```

**Comment by renatoathaydes** [comment]
Try replacing these lines:

```
task.systemProperty "com.athaydes.spockframework.report.projectName", "${project.getName()}"
task.systemProperty "com.athaydes.spockframework.report.projectVersion", "${project.getVersion()}"
```

With:

```
task.systemProperty "com.athaydes.spockframework.report.projectName", project.name
task.systemProperty "com.athaydes.spockframework.report.projectVersion", project.version
```

**Comment by nlazouzi** [comment]
The problem was the use of the closure. So just got rid of that and all worked fine. Thx.
I replaced the block with 
```
      project.afterEvaluate {
            project.tasks.each{
                if (it instanceof Test) {
                        it.systemProperty "com.athaydes.spockframework.report.projectName", "${project.getName().toString()}"
                        it.systemProperty "com.athaydes.spockframework.report.projectVersion", "${project.getVersion().toString()}"

                }
            }

        }
```

**Comment by renatoathaydes** [comment]
Good!
