### ISSUE TITLE
ConfigLoader doesn't read all configuration parameter as system properties

### ISSUE THREAD

**Issue by yilazius** [renatoathaydes/spock-reports#109]
Hi,

I'm configuring `spock-reports` by defining system properties. Unfortunately not all property settings are exposed as system-properties:
https://github.com/renatoathaydes/spock-reports/blob/594c24c94a1067a154f36313e7c32c3834c55f0a/src/main/groovy/com/athaydes/spockframework/report/internal/ConfigLoader.groovy#L13-L18

It would be quite convenient to be able to configure other system properties like inlineCss too.

Any help is appreciated :)

Cheers

**Comment by renatoathaydes** [comment]
That's right, only properties affecting all report creators are supported as system properties, the ones that relate to a particular report creator (such as `inlineCss`, which makes sense only for the HTML report creator) are not supported.

I will have a look at that.

**Comment by yilazius** [comment]
Thanks for your help @renatoathaydes - highly appreciated!
Did you gather any insights so far?

Best yilazius

**Comment by renatoathaydes** [comment]
I implemented most of it but  got sidetracked with other stuff... I will get back to it soon!

**Comment by renatoathaydes** [comment]
@yilazius my last commit made it possible to specify any property as a system property.

I will do some more manual tests, but this feature should be released soon.

Do you have time to build and test the current code in the `next` branch?

**Comment by renatoathaydes** [comment]
This was fixed in version 1.3.2.
