### ISSUE TITLE
Treat exotic method names as labels

### ISSUE THREAD

**Issue by kwangomango** [renatoathaydes/spock-reports#110]
Typically there is duplication between methods and block labels e.g.

Given: “today is Monday”
	    todayIsMonday()
When: "i determine what day tomorrow is"
            determineTomorrowDay()

so we have started combining the labels and methods into exotic method names. So a feature now reads like this:

Given: “today is Monday”()
When: "i determine what day tomorrow is"()

However, Spock reports treats this as if there was no block label. The only way to display it is by turning on 'vivid reports'.
Is it possible to treat an exotic method name as a block label?

**Comment by renatoathaydes** [comment]
The block name must be a String, not a method invocation... the two are separate things, even though as you show, they can be made to look really similar!

Unfortunately, I don't think it is possible to change that... unless you implement some Groovy AST Transformation, maybe...

Why don't you think showing vivid reports solves this problem? Seems like a good compromise to me.

**Comment by kwangomango** [comment]
Thanks, that is what i expected!
Not all of our Specs are written in this style yet, so we do not want to enable vivid reports for all Specs. Is it possible to enable/disable on a Spec level?

Thanks.

**Comment by renatoathaydes** [comment]
Not possible, sorry.

Even if your specs are not using this style, just add a String describing the blocks, and the code in the report is actually quite helpful, usually, as long as you implement more complicated stuff outside the spec block itself... just enable vivid reports and have a look at the results.

**Comment by kwangomango** [comment]
Thanks.
The issue is that we have two different audiences for our tests. Developers would be happy to see code in the Spock report but analysts and business users would not. I also am starting to find it a burden keeping the block labels in sync with the code, hence my want for using exotic method names as labels.
A good compromise for the vivid reports feature would be if there was a option to have the code blocks collapsed and hidden. Anyone who wanted to see the code could click a button to unhide the code blocks, rather like the +-, Expand All/Collapse All feature in the Fitnesse wiki:
http://fitnesse.org/FitNesse.UserGuide

**Comment by renatoathaydes** [comment]
Please create another ticket if you wish for the feature you've asked in the last message, but I think we can agree the original feature you requested cannot be added.
