### ISSUE TITLE
Could This be used to report Status to Sauce Labs?

### ISSUE THREAD

**Issue by goncalosoares** [renatoathaydes/spock-reports#111]
Hello,

I am using SauceLabs with Spock. I use the spock-reports on Jenkins but when I want to report status of a Job to Sauce Labs, I need to create a Test Watcher and Define it as a test Rule. This has though the issue that the test rule exception is not appearing because of an issue in spock. 

https://github.com/spockframework/spock/issues/118

But since the only thing I need is the result of the testing I thought that it could be interesting if I could use the report data collected by spock-reports.

Thank you so much :-)

**Comment by renatoathaydes** [comment]
I am not sure it helps, but if you look at the reports directory, spock-reports generates a file called `aggregated_report.json`. It gets updated each time a Spec finishes running.

It looks like this:

```json
{
  "com.myproject.AdminUIContentTypeTest": {
    "executedFeatures": [
      "Admin API endpoint #path serves JSON when Accept is set to #accept",
      "Unauthenticated admin endpoint #path serve text/html when Accept is set to #accept"
    ],
    "ignoredFeatures": [],
    "stats": {
      "failures": 0,
      "errors": 0,
      "skipped": 0,
      "totalRuns": 17,
      "successRate": 1.0,
      "time": 1328
    }
  },
  "com.myproject.AdminUIErrorHandlingTest": {
    "executedFeatures": [
      "/admin/login redirects to /admin/login/",
      "Sending an empty form to the login handler results in a 400 error",
      "Sending an unacceptable Accept header results in a 406 error and an error page",
      "Sending an unknown RPC operation results in a 200 with the expected error response model",
      "Sending no RPC operation results in a 200 with the expected error response model"
    ],
....
```

**Comment by renatoathaydes** [comment]
@KingSoares did you get the information you needed from the file I mentioned?

**Comment by ElCuervoSoares** [comment]
Sorry the looooonnnggg delay... I am trying it now :-)
