### ISSUE TITLE
Custom properties file is not loaded in Gradle

### ISSUE THREAD

**Issue by iriiiina** [renatoathaydes/spock-reports#115]
Hi
I am new to Gradle, so may be I do some obvious mistake, but I can't fix it in a while.

Report works fine with default properties, but it doesn't load my custom properties. I put them into `src/test/resources/` directory (according to https://rdmueller.github.io/spock-reports-with-gradle), changed some values, but on the next Spock test run console shows that default properties are still used (and nothing changes in the the report).

I tried different file names, like `com.athaydes.spockframework.report.IReportCreator.properties`, `IReportCreator.properties`, `SpockReports.properties` - nothing helps. I also tried to put file into `src/main/resources/` - still doesn't help.

I use Gradle 2.4, Spock-Reports 1.3.1, Intellij IDEA

**Comment by renatoathaydes** [comment]
Do you use Grails? The blog post you linked to is about Grails users only...

If you don't use Grails, then the config file should be placed at:

```
src/test/resources/com.athaydes.spockframework.report.IReportCreator.properties`
```

Let me know if that doesn't work for you.

**Comment by renatoathaydes** [comment]
Oh, sorry @iriiiina !!! I posted the wrong location...

It should be:

```
src/test/resources/META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties
```

**Comment by iriiiina** [comment]
Thank you a lot! That helped

**Comment by renatoathaydes** [comment]
You're welcome.
