### ISSUE TITLE
Is it possible to show response info in error section?

### ISSUE THREAD

**Issue by iriiiina** [renatoathaydes/spock-reports#116]
Is it possible to show response body and headers in error section in case of a test failure? Maybe I can do it using cutom template or printing it out inside the test (if that's the case, then how exactly? standard printing dosen't work).

**Comment by renatoathaydes** [comment]
Could you please show me your test assertion so I can try to help you with that?

**Comment by renatoathaydes** [comment]
I've done something like this in one of my tests:

```groovy
then: 'Assert some response has the right status code'
showResponse(response) && response.statusCode == 200

// somewhere else
def showResponse(response) {
    "status=${response.statusCode}\nheaders=${response.headers}\n${response.body}"
}
```

This uses the fact that a non-empty String (returned by `showResponse`) is considered `true` in boolean expressions, so the test will always pass if the other conditions are also true... and if the other conditions fail, the error will include the String created by `showResponse`.

Hope that helps.

**Comment by iriiiina** [comment]
Thank you for the quick answer, but unfortunately it didn't help: I see status code and header in the report, but instead of JSON body I see `com.jayway.restassured.internal.RestAssuredResponseImpl@49369868`:
<img width="858" alt="error" src="https://user-images.githubusercontent.com/5726961/29535080-378ce994-86c1-11e7-9a4a-67c5f01491b8.png">

**Comment by renatoathaydes** [comment]
Looking at [the docs](http://static.javadoc.io/com.jayway.restassured/rest-assured/1.4.5/com/jayway/restassured/internal/RestAssuredResponseImpl.html#body()) for `RestAssuredResponse`, I can see that you should be able to get the body with this:

```groovy
response.body().asString()
```

**Comment by iriiiina** [comment]
Thanks a lot! I did it with prettyPrint(), works great!
