### ISSUE TITLE
Is there a way to add the browser details as tag into the report

### ISSUE THREAD

**Issue by perwezalamnewscorp** [renatoathaydes/spock-reports#127]
When I run the test in multiple browser and wish to see the single report for all runs. Here it would be good if could show the browser details as tag, So we will be able to filter it by browser.

As this is the real use case where we would love to have in the report.

**Comment by renatoathaydes** [comment]
What tags do you have in mind? Like JUnit 5 Tags?

**Comment by perwezalamnewscorp** [comment]
Not exactly, I should have not called it as tag.
I mean to add the test environment details into the report, When my test are run in 3 different browser and different OS. Now I want to see the report categorized by browser name and OS name. So That It would be very easy to filter out the test and find the failure happened in which platform. 

But in the current way of implementation, It just will show all the report but not sure which one is from which environment. Cant identify easily in which browser it got failed until seeing the logs

So My suggestion is when navigating to particular spec file from index file, Show the result as shown below with test environment details
**For example**

**---MAC--**
**Chrome**
      Test 1
      Test 2

**Firefox**
     Test 1
     Test 2

**Safari**
    Test 1
    Test 2

**---Windows---**
**Chrome**
    Test 1
    Test 2

**Firefox**
    Test 1
    Test 2

Or in some other way if you have something in mind.

**Comment by renatoathaydes** [comment]
Sure, but please clarify where that information would come from. Test annotations? System properties? Looks like you're using Geb... does Geb allow us to get that information somehow?

**Comment by perwezalamnewscorp** [comment]
Yes I am using Geb and Spock framework only. Not sure how to get environment details at runtime. I will get back to you shortly when I get the work around.

**Comment by perwezalamnewscorp** [comment]
All these information should be made available by Geb tool only like selenium. Need to identify which api provide these information.

**Comment by perwezalamnewscorp** [comment]
I got the way to get the platform (OS Name) and browser name  and its version at runtime as follows.

driver.capabilities['browserName']
driver.capabilities['platformName']
driver.capabilities['version']

There are lots more capabilities are available and can be retrieved like this

driver.capabilities

I think this should solve the issue we discussed. Please let me know if want any more info

**Comment by renatoathaydes** [comment]
I will see how we can pull this information into spock reports in a general manner. Notice that Geb and Selenium are only used by web testing, whereas Spock itself is used for many other things... so a general solution is necessary that allows other frameworks to make this information available somehow to the reports....

**Comment by perwezalamnewscorp** [comment]
Yes, I agree with your point. Anyway just give a try to find general solution.

Thank you so much

**Comment by schhil** [comment]
Maybe Feature https://github.com/renatoathaydes/spock-reports/issues/123 would also help to solve this issue. A group of tests or even an individual test could add specific information to the test report, which the test creator finds useful to have.

**Comment by renatoathaydes** [comment]
Agree with @schhil ... @perwezalamnewscorp  let's continue this discussion on ticket #123 as I have implemented that already!
