### ISSUE TITLE
How to show only latest result, It should not preserve previous results

### ISSUE THREAD

**Issue by perwezalamnewscorp** [renatoathaydes/spock-reports#128]
I see that its does not clean up the exiting reports directory (means it preserve the previous results) every time when test are run. It override the result for the specs, that the test has been run and also it preserve the previous results for the spec test was not run.

But I want only latest result to be shown in my test report not the older one. Is this feature existed now ?

**Comment by renatoathaydes** [comment]
That's by design, if you want  a clean run, do `gradle clean check`.
