### ISSUE TITLE
How can I change the default language of spock report template from English to my local language?

### ISSUE THREAD

**Issue by WenRui13** [renatoathaydes/spock-reports#130]
the default language of spock test report template is English. How can I change the report template language to local language?

**Comment by WenRui13** [comment]
Is there anywhere to config it?

**Comment by renatoathaydes** [comment]
Unfortunately, we do not currently support other languages. This would be a cool feature to add, though! Let's see if someone from the community stands up to it or if not, I'll try to do it when I get some spare time.

**Comment by WenRui13** [comment]
looking forward it, thanks a lot.
