### ISSUE TITLE
Report does not show code blocks (vivid report)

### ISSUE THREAD

**Issue by amimas** [renatoathaydes/spock-reports#135]
Hello,

I must be doing something wrong. I cannot seem to get the spock reports to show code blocks even though I have enabled it via system property in my Gradle script.

I have a custom sourceSet called "integrationTest" in my project. In my Gradle build script, I have the following snippet

```gradle
integrationTest {
    //configuration for spock-reports
    systemProperty 'com.athaydes.spockframework.report.showCodeBlocks', true
    systemProperty 'com.athaydes.spockframework.report.testSourceRoots', sourceSets.integrationTest.groovy.srcDirs
    systemProperty 'com.athaydes.spockframework.report.projectName', project.name
    systemProperty 'com.athaydes.spockframework.report.projectVersion', "$version ($buildLabel)"
}
```

I'm using `spock-reports` version *1.4.0* but also tried with version *1.3.1*. In each cases, spock report is being generated. When I click on a specification link, it shows all the features for that specification but I don't see the code blocks. It's as if I didn't even set the system properties.

I know the system property is working because after setting them in my snippet above, the spock report now hows Project Name and Version information. So, not really sure why `showCodeBlocks` is not working.

**Comment by renatoathaydes** [comment]
Please run the tests with `gradle <test-task> --debug` and see if you find any messages from `spock-reports` that might indicate what's wrong.

**Comment by amimas** [comment]
Thank you for the quick reply. I ran the tests in debug mode but didn't find anything out of the ordinary when searching for `spock-reports`. Here are some of the debug logs.

```
13:55:32.620 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder] dependency: com.athaydes:spock-reports:1.4.0 from-conf: integrationTestCompile to-conf: null is filtered.
13:55:32.872 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve spock-reports.jar (com.athaydes:spock-reports:1.4.0)' completed
13:55:32.806 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for com.athaydes:spock-reports:1.4.0 using repositories [maven, maven2]
13:55:32.806 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'com.athaydes:spock-reports:1.4.0' in 'maven'
13:55:32.806 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using com.athaydes:spock-reports:1.4.0 from Maven repository 'maven'
13:55:32.806 [DEBUG] [org.gradle.internal.component.model.ComponentAttributeMatcher] No candidates for {org.gradle.usage=java-api}, selected matching fallback com.athaydes:spock-reports:1.4.0 configuration default
13:55:32.870 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve spock-reports.jar (com.athaydes:spock-reports:1.4.0)' started
13:55:32.870 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve slf4j-api.jar (org.slf4j:slf4j-api:1.7.25)' started
13:55:32.870 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'spock-reports.jar (com.athaydes:spock-reports:1.4.0)' in resolver cache: /Users/amimas/.gradle/caches/modules-2/files-2.1/com.athaydes/spock-reports/1.4.0/1f649285e1144d246dd1af28f7b865a2ad24a698/spock-reports-1.4.0.jar
13:55:32.871 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found artifact 'slf4j-api.jar (org.slf4j:slf4j-api:1.7.25)' in resolver cache: /Users/amimas/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar
13:55:32.871 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Resolve slf4j-api.jar (org.slf4j:slf4j-api:1.7.25)'
13:55:32.871 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve slf4j-api.jar (org.slf4j:slf4j-api:1.7.25)' started
13:55:32.871 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Resolve slf4j-api.jar (org.slf4j:slf4j-api:1.7.25)'
13:55:32.871 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Resolve spock-reports.jar (com.athaydes:spock-reports:1.4.0)'
13:55:32.872 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve slf4j-ext.jar (org.slf4j:slf4j-ext:1.7.25)' started
```

I was doing some trial and error and I'm able to get it to work now. It seems, in my case (probably because it's a custom sourceSet), I need to set `com.athaydes.spockframework.report.testSourceRoots` system property. As you can see in my original post, I have done that but somehow the spock-reports is not getting the value.

If I set the system property to hard-coded path like below, it works
```gradle
integrationTest {
    //configuration for spock-reports
    systemProperty 'com.athaydes.spockframework.report.showCodeBlocks', true
    systemProperty 'com.athaydes.spockframework.report.testSourceRoots', "src/integration-test/groovy"
    systemProperty 'com.athaydes.spockframework.report.projectName', project.name
    systemProperty 'com.athaydes.spockframework.report.projectVersion', "$version ($buildLabel)"
}
```

So, the following line was the problem

`systemProperty 'com.athaydes.spockframework.report.testSourceRoots', sourceSets.integrationTest.groovy.srcDirs`

Not sure why that didn't work. That seems to be correct Gradle DSL and if I add the `println sourceSets.integrationTest.groovy.srcDirs` in Gradle script, I get correct path but a full system path.

Could that be the problem? I am guessing `spock-reports` is expecting a relative path from the project directory, but is there a way I can set relative path using Gradle instead of hardcoding it myself?

**Comment by renatoathaydes** [comment]
The system property is always a String. When you set it to `sourceSets.integrationTest.groovy.srcDirs` you get a `List`, which when converted to String looks like `['src/integration-test/groovy']`. This is not recognized as a directory, so Spock just can't find your sources.

Try this instead:

```groovy
systemProperty 'com.athaydes.spockframework.report.testSourceRoots', sourceSets.integrationTest.groovy.srcDirs.join(File.pathSeparator)
```

**Comment by amimas** [comment]
Thank you. That worked nicely.

What do you think of `spock-reports` providing some feedback in this type of scenario where `showCodeBlock` is enabled but the report doesnt contain source codes because the sources cannot be found.

Maybe in the report or in the terminal as part of the execution phase. It's hard to tell otherwise why the report doesn't contain any sources.

**Comment by renatoathaydes** [comment]
I suspect you don't have a `slf4j-api` logger implementation in the test classpath. Pretty sure that if you did, you would see a warning.

Can you try to add this dependency to your project, as explained in the [README](https://github.com/renatoathaydes/spock-reports#customizing-spock-reports-logging) page?

```groovy
testCompile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.13'
```
