### ISSUE TITLE
No signature of method Utils.specAnnotation

### ISSUE THREAD

**Issue by ntung** [renatoathaydes/spock-reports#136]
Hi,
According to the [document](https://rdmueller.github.io/Spock-Reports-with-Grails-2.5/), I am trying to configure spock reports in my grails 2.5.5 based application. The application is running under JDK 1.8. I am curious at how [the issue](https://github.com/renatoathaydes/spock-reports/issues/44) was managed properly under JDK 1.8 as confirmed by the issue raiser.

I attach here the spock report templates having modified a bit.

The error I got is
```
Feb 27, 2018 5:04:42 PM org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
WARNING: Unexpected error creating report: groovy.lang.MissingMethodException: No signature of method: static com.athaydes.spockframework.report.util.Utils.specAnnotation() is applicable for argument types: (com.athaydes.spockframework.report.internal.SpecData, java.lang.Class) values: [com.athaydes.spockframework.report.internal.SpecData@7a86e414, ...]
```
[spockreporttemplate.zip](https://github.com/renatoathaydes/spock-reports/files/1763929/spockreporttemplate.zip)

**Comment by renatoathaydes** [comment]
Are you using version 1.4.0?

**Comment by ntung** [comment]
@renatoathaydes I am using version 1.2.5. See configuration below
`test "com.athaydes:spock-reports:1.2.5"`

**Comment by renatoathaydes** [comment]
As you saw in the ticket #44 this has been already fixed. Just upgrade to the latest version.
