### ISSUE TITLE
SpockReportsSpecificationExtension writes to System.out

### ISSUE THREAD

**Issue by quachc** [renatoathaydes/spock-reports#139]
At the end of every test run I see the following output written to the console:

```
Resetting data of spec: foo.bar.BazSpec
  Headers: []
  extraInfo: [java.lang.Object@<hash>,...]
```

After some exploring I found a couple of `println` statements in `com.athaydes.spockframework.report.extension.InfoContainer#resetSpecData` which match with the output.

According to the README spock-reports uses SLF4J for logging (and I see it used often in the code), so I'm pretty sure this is left there by mistake...

**Comment by renatoathaydes** [comment]
Yeah, that was a mistake. I will fix it in the next release! Thanks.

**Comment by quachc** [comment]
Cool, thx!
