### ISSUE TITLE
Customize report name

### ISSUE THREAD

**Issue by palvik** [renatoathaydes/spock-reports#140]
Is it any option to provide report name different than spec class name? in index.html and report html? for example, set the name by a property or envirenment variable #

**Comment by renatoathaydes** [comment]
The name of the spec cannot be changed , but try using these settings (in config file or system property):

```
com.athaydes.spockframework.report.projectName=My Project
com.athaydes.spockframework.report.projectVersion=1.0-beta
```

**Comment by renatoathaydes** [comment]
Also, you can use Spock annotations like `@Title` and `@Narrative`.
See https://stackoverflow.com/questions/30981235/spocks-narrative-and-title-annotations
