### ISSUE TITLE
Displaying variables in step description

### ISSUE THREAD

**Issue by ghost** [renatoathaydes/spock-reports#143]
Hi,
I have a problem with displaying variables in steps, that are not defined in "where" block. Is there any way to provide variables in steps description? It is not possible to introduce those in "where" table.

Example:

```
import enpoint_name

@Unroll
def "This is a test where a=#a and b=#b"() {
given: "Environment setup for ${endpoint_name}"
setUp(endpoint_name)

when: ...

then: ...

where:
a | b
1 | 2
3 | 4
}
```

**Comment by markhu** [comment]
I've done a kludge where I make a dummy column containing the unchanging env var. Crude, but effective. :)

**Comment by renatoathaydes** [comment]
You can also use the `reportInfo "Something something"` function to write stuff in the report...

https://github.com/renatoathaydes/spock-reports#how-to-use-it

**Comment by ivtm86** [comment]
Hi, 
feature reportInfo not working for me. 
I use version **spock-reports-1.5.0.jar**
this is my code snipped
 ```
 def "Step 1"(){
            def rl = "Simple reportline"
            given: "testdata"
            expect: 
            reportInfo rl
        }
```

**Comment by renatoathaydes** [comment]
It works for me:

![screen shot 2018-05-29 at 4 33 27 pm](https://user-images.githubusercontent.com/1901277/40665672-1e846cfe-635e-11e8-9329-4cdc18c9daa2.png)

**Comment by ivtm86** [comment]
What am I doing wrong ;-(
This is my result 

![image](https://user-images.githubusercontent.com/18352579/40701392-0d31539c-63de-11e8-8b7b-59d711f7e801.png)

**Comment by renatoathaydes** [comment]
you're using some template report, I guess... the template has to include the information...

For each feature that ran, do this:

```groovy
def extraInfo = utils.nextSpecExtraInfo( specData )

for ( info in extraInfo ) {
    // TODO write 'info' to the report
}
```

**Comment by ivtm86** [comment]
Hi Renato,
thanks for your effort.
you are right, i use my custom html (not md) template
and i implement your code snippen 
```
<%features.eachFeature { name, result, blocks, iterations, params ->%>
        //.... some code
        <% def extraInfo = utils.nextSpecExtraInfo(data); for(info in extraInfo){%>
		<p>$info</p>
	<%}%>
       //some code ...
<%}%>
```

but created report is unusual
some reportInfos are not reported and some reported but not in the rigtht step.

```
Test: Step 1
Status: PASS
Given: Step1
ReportInfodata 6
--------------------
Test: Step 2
Status: PASS
Given: Step2
------------------
Test: Step 3
Status: PASS
Given: Step3
ReportInfodata 7
--------------------
Test: Step 4
Status: PASS
Given: Step4
--------------------
Test: Step 5
Status: PASS
Given: Step 5
ReportInfodata 8
--------------------------
Test: Step 6
Status: PASS
Given: Step 6
------------------------------
Test: Step 7
Status: PASS
Given: Step 7
ReportInfodata 9
-------------------------------
Test: Step 8
Status: PASS
Given: Step 8
---------------------------
Test: Step 9
Status: PASS
Given: Step 9
ReportInfodata 10
-----------------------------
Test: Step 10
Status: PASS
Given: Step 10
```
And second Question. 
I need one like  solution to use reportHeaders 
```
 <% def headerInfo = utils.specHeaders( data )%>
<h2>Header: $headerInfo</h2>
//headerInfo is null
```

**Comment by renatoathaydes** [comment]
Have a look at the [default md template](https://raw.githubusercontent.com/renatoathaydes/spock-reports/master/src/main/resources/templateReportCreator/spec-template.md).
