### ISSUE TITLE
Missing code blocks in tests with examples

### ISSUE THREAD

**Issue by mfriedenhagen** [renatoathaydes/spock-reports#147]
Given I set `com.athaydes.spockframework.report.showCodeBlocks=true` 
When I look at the report of tests with examples
Then I expect the code blocks to show.
* However source code is not rendered.

**Comment by renatoathaydes** [comment]
There are tests proving that it works in both cases.
Please be more specific.

Which version you're using?
Do you change the location of the source code or use the default? 
Do you run tests from source or from a jar?

Try to enable spock-reports logs as explained in the README page and see if there's any error.

**Comment by mfriedenhagen** [comment]
Hi, thanks for the quick feedback.
* I now created https://github.com/mfriedenhagen/spock-reports-147
* Please checkout and run `./mvnw clean verify`.
* In produced target/spock-reports/com.github.mfriedenhagen.spockreports147.AppTest.html I do not see the code in the two data driven tests.

OS/JVM Specs:
```
$ ./mvnw -v                                                                                                                                                                                            spock-reports-147[master]-
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: /Users/USER/.m2/wrapper/dists/apache-maven-3.5.3-bin/6rtk6r8hiu511erccgp64thica/apache-maven-3.5.3
Java version: 1.8.0_172, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
```

**Comment by mfriedenhagen** [comment]
I just retested and removed `com.athaydes.spockframework.report.outputDir` completely from the `pom.xml`, the report in `build/spock-reports/com.github.mfriedenhagen.spockreports147.AppTest.html` is missing the source as well for the data-driven tests.

**Comment by renatoathaydes** [comment]
Hi,

I checked out the example project, you're right, it's missing the code in the reports.

@hexmind do you have time to give us a hand with this issue?

**Comment by mfriedenhagen** [comment]
BTW: 
* why is `WARN com.athaydes.spockframework.report.SpockReportExtension - Got configuration from Spock: com.athaydes.spockframework.report.internal.SpockReportsConfiguration([:])` a warning?
* Shouldn't this be something like `INFO - Using default configuration from com.athaydes.spockframework.report.internal.SpockReportsConfiguration`?

**Comment by renatoathaydes** [comment]
I will change that message to INFO.

**Comment by renatoathaydes** [comment]
@mfriedenhagen  I found out that if you remove the parameter from the test method (which is not needed anyway) it works.

So, spock-reports for some reason fails to identify methods with parameters as test methods.

For now, just remove the parameters from test methods and it will work, I will see if there's a way to correctly identify these methods as being test methods.

**Comment by hexmind** [comment]
Not earlier than 10 days

28.05.2018 9:38 PM "Renato Athaydes" <notifications@github.com> napisał(a):

Hi,

I checked out the example project, you're right, it's missing the code in
the reports.

@hexmind <https://github.com/hexmind> do you have time to give us a hand
with this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/renatoathaydes/spock-reports/issues/147#issuecomment-392562852>,
or mute the thread
