### ISSUE TITLE
Best way to inject custom variables into custom reports?

### ISSUE THREAD

**Issue by StephenOTT** [renatoathaydes/spock-reports#150]
Been looking over the custom reports for Markdown:

My use case is that I have some javascript i want to embed within the spec template:
For each spec I am generating some data (arrays, maps, strings, etc) that i want to inject into the template to populate variables being used within the Javascript.

I see there is the `reportInfo` method, but I did not come across anything related to more complex named variable access.

Thanks!

**Comment by StephenOTT** [comment]
Best i could tell from the md template examples I could merge all of the data into a single json object and inject it into "reportInfo" and then access it similar to the spec template:

```
    def writeExtraInfo = { extraInfo ->
        if ( extraInfo ) {
            extraInfo.each { info ->
                out << '* ' << info << '\n'
            }
        }
    }
```

**Comment by StephenOTT** [comment]
In the mean time, my workaround was to create a hashmap that i inject into reportInfo() then each iteration/feature i do extraInfo[0] to get the hashmap.

**Comment by StephenOTT** [comment]
@renatoathaydes any advice on this?

This is what i am doing with the variable in question:

![spock-bpmn-coverage-digitalstate - v5](https://user-images.githubusercontent.com/1994838/41167201-42977956-6b10-11e8-8979-085a0e54c083.png)


In this case i am only use a single call of reportInfo() at the end / cleanup() of the feature to provide the report with a Map that is used to inject variables into the JS that runs the Diagram builder (BPMN Coverage).  But I would like to now get into adding additional options for reportInfo() usage on a per block/statement basis, and this conflicts with my current workaround.

Thanks!

**Comment by renatoathaydes** [comment]
I don't really see what's the problem you're having, to be honest. `reportInfo(info)` takes any `Object`, so you can put any information in it that you want.
 `utils.nextSpecExtraInfo( data )` gives you the information for the next iteration of the given spec. Once you get that information, you can write any code you want to, using any type you want.

You could have your own complex type passed into `reportInfo`... including something that "knows" which block you're in.

```groovy
class SuperReportInfo {
  Map jsVariables = [:]
  String blockName = ''
  String evenMoreInfo = ''
}
```

Then, from the report, do:

```groovy
given:
reportInfo new SuperReportInfo(blockName: 'given', jsVariables: [a: 1, b: 2])
```

Now you have access to the `SuperReportInfo` instance in the template. Are you sure you need anything else?

**Comment by StephenOTT** [comment]
Your solution works.  I was originally detecting the Map in the array.  I was just looking if there was a way to name the report info rather than in the array so save the cycle through the array.  

Your solution works and will use that.  thanks!
