### ISSUE TITLE
Best method for adding additional files into  /target/spock-reports during report creation

### ISSUE THREAD

**Issue by StephenOTT** [renatoathaydes/spock-reports#153]
Is there any utils for helping with this?  Browsing through code, i did not see any, but wanted to double check

thanks

**Comment by renatoathaydes** [comment]
What kind of files? If they are static files, then I suggest using your build file to copy them. The location the report files go into is determined by your build system.

**Comment by StephenOTT** [comment]
Yes static files. Yes I had added them into the build Pom. Was just thinking You had added a config option as well in the reports configs/properties 

Thanks
