### ISSUE TITLE
Access feature time in specTemplate or summaryTemplate

### ISSUE THREAD

**Issue by verticalrider** [renatoathaydes/spock-reports#154]
I am using TemplateReportCreator but I cannot seem to be able to access the duration (time) for each feature like it it available in the default Gradle / spock test reports (screenshot attached).

I am only able to access the Total Time at Specification level:
```
<% def stats = utils.aggregateStats( data ) %>
<% data.each { name, map ->
	def s = map.stats
%>
<div>${fmt.toTimeDuration(s.time)} seconds</div>
<%
	}
%>
```

![chrome_2018-07-17_09-30-23](https://user-images.githubusercontent.com/41321188/42802762-20d0579a-89a4-11e8-9041-4b9552b62f47.png)

Is there any way to access this data in Spock Reports?

**Comment by renatoathaydes** [comment]
They are calculated independently. spock-reports calculates the times itself based on Spock's hooks (which in turn depend on the JUnit hooks). I don't know what Gradle uses, but I would expect it to also use the JUnit hooks for that... so the times should be very similar, if they are not similar, one of them is wrong :) would be interesting to know which one.

**Comment by renatoathaydes** [comment]
This can be done after version 1.6.1 that I just released.
See the default MD report template for an example (above commit).
