### ISSUE TITLE
Report info in markdown template is not mapped correctly when feature is ignored

### ISSUE THREAD

**Issue by tilmanginzel** [renatoathaydes/spock-reports#157]
Hi,

when a feature is marked as ignored, report extra infos are not mapped correctly to the features in the markdown template. It is working correctly in the HTML report.

Example Spec:
```groovy
class Spec extends Specification {

    def "first"() {
        expect:
        reportInfo("first report info")
        true
    }

    @Ignore
    def "second"() {
        expect:
        true
    }

    def "third"() {
        expect:
        reportInfo("second report info")
        true
    }
}
```

Current result:
```markdown
## Features

### first
* first report info

Result: **PASS**

* Expect: 

reportInfo("first report info")
true

### second
* second report info

Result: **IGNORED**

* Expect: 

true

### third

Result: **PASS**

* Expect: 

reportInfo("second report info")
true
```

Expected result:
```markdown
## Features

### first
* first report info

Result: **PASS**

* Expect: 

reportInfo("first report info")
true

### second

Result: **IGNORED**

* Expect: 

true

### third
* second report info

Result: **PASS**

* Expect: 

reportInfo("second report info")
true
```

This can be fixed by adding a simple check in the [spec-template.md](https://github.com/renatoathaydes/spock-reports/blob/master/src/main/resources/templateReportCreator/spec-template.md) before line 70:
```groovy
 if (result != "IGNORED") {
     if ( utils.isUnrolled( delegate ) ) {
        writeExtraInfo( utils.nextSpecExtraInfo( data ) )
     } else {
        // collapse all iterations
        (1..iterations.size()).each {
            writeExtraInfo( utils.nextSpecExtraInfo( data ) )
        }
     }
 }
```

If you want I can provide a pull request for this.

Cheers :)

**Comment by renatoathaydes** [comment]
Send a PR if you have time! There's some other small issues to fix, I might fix a few of those and then make a release in the next few days.
Thanks.

**Comment by tilmanginzel** [comment]
Alright, I will do that later today. Should I base it off the `next` or `master` branch? `next` is currently behind master.

**Comment by renatoathaydes** [comment]
Sorry, just pushed a clean `next` branch off `master`... please target `next`.
