### ISSUE TITLE
Generating reports for integration tests

### ISSUE THREAD

**Issue by virgiliu-ratoi-ec-ext** [renatoathaydes/spock-reports#160]
Hi,

I tried using `spock-reports`, it is very nice and useful but I discovered that, at least on our project and with the default settings, it generates reports only for the unit tests. Our convention is that unit tests end in `Test`, `Spec` or `Documentation` while integration tests end in `TestIT`. This is handled via `Maven Surefire` and `Failsafe`.

How can we include the `Spock` integration tests which are run with `Maven Failsafe`?

**Comment by renatoathaydes** [comment]
Spock Reports will work as long as your tests are run by the Spock framework and spock-reports is in the test classpath. Please check your configuration as it should work fine... if it doesn't please post a minimal example pom which can be used to reproduce the problem so I can investigate.

**Comment by renatoathaydes** [comment]
Try to enable spock-reports logging [as shown in the README](https://github.com/renatoathaydes/spock-reports#customizing-spock-reports-logging).
