### ISSUE TITLE
Problems in displaying extended ASCII charset for non UTF-8 sources

### ISSUE THREAD

**Issue by siaspa** [renatoathaydes/spock-reports#167]
![capture](https://user-images.githubusercontent.com/15030979/49218218-22f48f00-f3d0-11e8-88e8-f039d6955624.PNG)
Hi, 

I've got a problem with the resulting HTML report. The source files are encoded with **Cp1252** charset, but the HTML is always produced with the **UTF-8** charset.  

I tried to recompile the project (1.6.1) changing the charset for the HTML output and everything works fine. Maybe the charset the project is using can be read from the gradle project. Anyway, since the one that we should specify is the HTML charset, we can specify it somewhere (SpockConfig.groovy?)

```gradle
project.tasks.withType(JavaCompile) {
	options.encoding = "windows-1252"
}
		
project.tasks.withType(GroovyCompile) {
	groovyOptions.encoding = "windows-1252" // defaults to UTF-8
}
```

This change worked for me (obviously all the HTML tests failed)

com.athaydes.spockframework.report.internal.**AbstractHtmlCreator**<T>

```java
    String reportFor( T data ) {
....
        builder.html {
            head {
               // Original code
               // meta( 'http-equiv': 'Content-Type', content: 'text/html; charset=utf-8' )
                
              //Workaround
              meta( 'http-equiv': 'Content-Type', content: 'text/html; charset=ISO-8859-1' )
```

David Obber

**Comment by siaspa** [comment]
![capture](https://user-images.githubusercontent.com/15030979/49218185-0bb5a180-f3d0-11e8-9f4c-b1411314a94f.PNG)

**Comment by renatoathaydes** [comment]
Hi, thanks for the detailed report. I am currently looking at this issue and will try to come up with a fix for the next release.

**Comment by siaspa** [comment]
Yes! it works perfectly! Thank you
