### ISSUE TITLE
Geb screenshot not working

### ISSUE THREAD

**Issue by Kanti1702** [renatoathaydes/spock-reports#168]
spock-reports version : com.athaydes:spock-reports:1.6.1

Previously with 'org.spockframework:spock-core:1.0-groovy-2.4' , I was able to get screenshots.

But with this extension, I have to use 'org.spockframework:spock-core:1.1-groovy-2.4' and due to this I'm not getting any screenshots.

Is there any way that I can use this extension as well screenshots also working fine?

I don't want to use another extension to get screenshots working.

Test Environment is with Geb and chrome driver.

**Comment by renatoathaydes** [comment]
Are you using https://github.com/AOEpeople/geb-spock-reports?

**Comment by Kanti1702** [comment]
We are using com.athaydes:Spock-reports:1.6.1 for report.

**Comment by renatoathaydes** [comment]
> Previously with 'org.spockframework:spock-core:1.0-groovy-2.4' , I was able to get screenshots.

What do you mean? I am not aware of Spock supporting screenshots, or ever having done so. Are you talking about Geb reports, perhaps?

spock-reports seems unrelated to this issue. If you want me to fix anything, please be more clear about what is the exact problem that spock-reports is causing for you.
