### ISSUE TITLE
There's no line number of error in case @Title is used

### ISSUE THREAD

**Issue by viastakhov** [renatoathaydes/spock-reports#169]
There's no line number of error in case @Title is used in test.

**Steps to reproduce.**

**Preconditions**:
1. I have test, annotated with @Test, which is executed with error
2. com.athaydes.spockframework.report.showCodeBlocks = true

**Steps**:
1.  Execute test;
2. Check report \index.html

ER: There is code line of error in relevant block where error was occurred.
AR: There isn't code line of error, only stack trace available in bottom of the report

**Work around**:
Either delete @Title annotation or use @Narrative instead.

**Comment by renatoathaydes** [comment]
Will release the fix soon!
