### ISSUE TITLE
Question: where to put the .properties file in a Grails project

### ISSUE THREAD

**Issue by rdmueller** [renatoathaydes/spock-reports#17]
Do you have any idea where to put the configuration for the spock-reports in a Grails project?

Might it even be possible to configure it in the Config.groovy? 

Everything I tried failed until now...

**Comment by alexboly** [comment]
It doesn't work for me. I tried putting the .properties file with its path META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties in:

* grails-app/config/
* web-app/config/
* test/functional/

None of this works. The report is not created and there's no error reported.

I'm using grails 2.5.0. 

@rdmueller do you have an example of this working? Thanks!

**Comment by alexboly** [comment]
According to a tweet from @rdmueller "The templates reports currently don't work for jdk8" https://twitter.com/RalfDMueller/status/618778357199699969 . I'm using jdk8.

I still don't know how to configure standard reports though.
