### ISSUE TITLE
Spec with Ignore annotation is not included to report at all

### ISSUE THREAD

**Issue by viastakhov** [renatoathaydes/spock-reports#170]
In accordance with [Spock Framework Reference Documentation, version 1.2](http://spockframework.org/spock/docs/1.2/all_in_one.html#_ignore)

> To ignore a whole specification, annotate its class:
```groovy
@Ignore
class MySpec extends Specification { ... }
```
> In most execution environments, ignored feature methods and specs will be reported as "skipped".

In my case when I add annotation **@Ignore** to my class and run this test then I can't see skipped test in the Spock Report.

Note: it's able to add description the  **@Ignore** annotation as well , i.e.: 
```groovy
@Ignore("This test should be skipped due to ...")
class MySpec extends Specification { ... }
```

**Comment by viastakhov** [comment]
@renatoathaydes , when I set description in annotation
```groovy
@Ignore("This test should be skipped due to ...")
```
then this description is not added into the report.
Can you fix it?

**Comment by renatoathaydes** [comment]
I can have a look... but please notice that this is an open source project, it would be a nice contribution if you could try do do it yourself and help make the project better.
