### ISSUE TITLE
index.html is not getting created

### ISSUE THREAD

**Issue by sadaphalpramod** [renatoathaydes/spock-reports#171]
I am not able to see index.html in output location. Able to see only Spec.html.
Following are the dependencies added in pom.

       <dependency>
            <groupId>com.athaydes</groupId>
            <artifactId>spock-reports</artifactId>
            <version>1.6.1</version>
            
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.8.0-beta4</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.8.0-beta4</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.3.0-alpha4</version>
            <scope>test</scope>
        </dependency>

**Comment by renatoathaydes** [comment]
Try removing the `<exclusions>` block.

**Comment by sadaphalpramod** [comment]
I tried by removing  <exclusions> block, but it is still not working.

**Comment by sadaphalpramod** [comment]
here are my observations on this-
1. I have created spring boot application. After starting spring boot app i am executing api exposed in it. In that api (rest controller) there is logic to invoke Spock tests(using Junit runner). I am able to run Spock specs from there successfully. I am getting Spock reports in html files for every spec but i am not getting  index.html and aggregated_report.json
index.html and aggregated_report.json are not created in below code. Individual spec reports are getting created.
   ```
 @GetMapping(value = "/testurl", produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity init() throws IOException {
        System.setProperty("com.athaydes.spockframework.report.outputDir", "src/main/resources/templates/");
        FileUtils.cleanDirectory(new File("src/main/resources/templates/"));
        JUnitCore.runClasses(SpockTestSampleSpec.class, SpockTestSample2Spec.class);

        return new ResponseEntity(HttpStatus.OK);
    }
```

2. In scenario, when i execute code which i have written for rest controller from `public static void main` method then index.html is getting created along with aggregated_report.json 

index.html is getting created in below code:
   ```
 public static void main(String[] args) throws IOException {
        System.setProperty("com.athaydes.spockframework.report.outputDir", "src/main/resources/templates/");
        FileUtils.cleanDirectory(new File("src/main/resources/templates/"));
        JUnitCore.runClasses(SpockTestSampleSpec.class, SpockTestSample2Spec.class);

    }
```

**Comment by renatoathaydes** [comment]
This is not how you use Spock and spock-reports.
Please read the documentation and follow the recommended usage.
I cannot assist you with specifics on Spring Boot and other methods of running tests that are not following any of the instructions provided in the README page.
