### ISSUE TITLE
Spock spec not initializing @Rule annotated field after adding spock-reports

### ISSUE THREAD

**Issue by Shagilton** [renatoathaydes/spock-reports#176]
I am fairly new to spock framework. I added spock-reports to my project recently. I used the Gradle dependency to do so (snippet below)
```
dependencies {
    // mandatory dependencies for using Spock
    compile "org.codehaus.groovy:groovy-all:2.5.7"
    compile "org.spockframework:spock-core:1.3-groovy-2.5"
    compile( 'com.athaydes:spock-reports:1.6.2' ) {
        transitive = false // this avoids affecting your version of Groovy/Spock
    }
    // optional dependencies for using Spock - Please remove as appropriate
    compile "org.hamcrest:hamcrest-core:1.3" // only necessary if Hamcrest matchers are used
    compile "net.bytebuddy:byte-buddy:1.9.3"          // allows mocking of classes (in addition to interfaces)
    compile "org.objenesis:objenesis:2.6"    // allows mocking of classes without default constructor (together with CGLIB)


    // https://mvnrepository.com/artifact/org.reflections/reflections
    compile group: 'org.reflections', name: 'reflections', version: '0.9.10'// Reflection Utilities used for this specific example
    // https://mvnrepository.com/artifact/org.slf4j/slf4j-api
    compile group: 'org.slf4j', name: 'slf4j-api', version: '1.6.1'
    // https://mvnrepository.com/artifact/org.slf4j/slf4j-simple
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.6.1'

    compile group: 'org.codehaus.groovy.modules.http-builder', name: 'http-builder', version: '0.7.1'//Used for RESTClient

}
```

Below is my SpockConfig.groovy file in the classpath:
```
spockReports {
    set 'com.athaydes.spockframework.report.showCodeBlocks' : false
    set 'com.athaydes.spockframework.report.testSourceRoots' : 'src/main/groovy'
    set 'com.athaydes.spockframework.report.outputDir' : '/Users/username/Documents/tbd/results'
    set 'com.athaydes.spockframework.report.internal.HtmlReportCreator.enabled' : true
}
```

I am using the below gradle task to generate a fatJar :

```
task runnableTestJar(type: Jar) {

    manifest {
        attributes 'Implementation-Title': 'QA Test Suite',
                'Implementation-Version': version,
                'Main-Class': "com.company.qa.app.RegressionTestRunner"
    }

    from sourceSets.test.output.classesDirs
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } } {
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
        exclude 'META-INF/NOTICE*'
        exclude 'META-INF/LICENSE*'
    }
    with jar
}
```

Eventhough it works when I run using the IDE, when I run the jar, I could see a NullPointerException for the below Test ($name is null):

```
class UsingJUnitRulesSpec extends Specification {
  @Rule TestName name

  def "retrieve test name at runtime"() {
    println "entering '$name.methodName'"
    expect: 1 + 1 == 2
    println "leaving '$name.methodName'"
  }
}
```

I understand that it could be something that I am doing wrong during packaging, but I am unable figure out what it is. Could someone please help me with this?

**Comment by renatoathaydes** [comment]
Hi @Shagilton . Can you explain why you believe this is a bug in Spock Reports and not in Spock itself? When you don't add a dependency on spock-reports, does it work?

I find it hard to see how spock-reports could be related to this issue. More likely, your test runner is not using `Sputnik`, the Spock JUnit test runner, as it should.

**Comment by Shagilton** [comment]
Hi @renatoathaydes, Thank you so much for your prompt response. I was able to figure out why the issue occurred, and it is not related to spock-reports directly. It was working when the spock-reports dependency was taken out, and that is why I thought of posting this question here.

The issue was that the file `org.spockframework.runtime.extension.IGlobalExtension` in `META-INF/services` of `spock-core` was getting replaced by the one in `spock-reports` when I was building the fat jar using gradle. This led to the missing config `org.spockframework.runtime.extension.builtin.RuleExtension`.

I am using `JUnitCore.runClasses(specifications)` to run the spock specification and it seems to be working fine. Do you feel that this is a bad idea and that I must be using Sputnik?

Thank you so much for taking the time to reply. I appreciate it.

**Comment by renatoathaydes** [comment]
Ah great... fat jars can cause problems like this easily... Try to use the shade plugin as that plugin can merge the resources from all jars.
I believe you should use `Sputnik` otherwise Spock features like test case examples will not work. But I've never tried, it would be odd if it worked and Sputnik were redundant!

**Comment by Shagilton** [comment]
I will try to use plugins to generate fat jars from now on, to avoid such issues. This is the first time I ran into a similar issue, and it was a good learning. 

As you mentioned, It is odd that `JUnitCore` runs all the spock specification examples in the sample github repo.  I will do a bit more digging to see if I can learn more about `Sputnik` runner as well, just in case.

Glad that it all worked out well. Thanks again for your support. Cheers !!
