### ISSUE TITLE
cannot generate spock report

### ISSUE THREAD

**Issue by I505103** [renatoathaydes/spock-reports#178]
Hi, I want to generate Integration test spock report , and I have configured all the dependencies introduced in readme,but my project still cannot generate spock report, it can only generate direct test result.  I tryed to debug, and found the spock-reports library has not been [loaded.](url) I configure other projects with the same method, they can generate reports. Can you give me some suggestions? Thank you so much~

**Comment by renatoathaydes** [comment]
Please show your dependencies configuration and try enabling spock-reports logging as explained in the README.

**Comment by I505103** [comment]
After enabling spock-reports logging as README and upgrade other configuration, it can generate spock-reports now. Thank you so much , I will close this issue :)
