### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by rdmueller** [renatoathaydes/spock-reports#18]
if the strings in your tests contain utf-8 characters (like german umlauts "äüö"), the generated html output will display them with the wrong encoding. This can easily be fixed by adding the utf-8 encoding to the html header:

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

**Comment by renatoathaydes** [comment]
Finally this fix has been released!! Version 1.2.4 is out! Thank you!

**Comment by rdmueller** [comment]
thanx!
