### ISSUE TITLE
Generating multiple different types of reports

### ISSUE THREAD

**Issue by meierw** [renatoathaydes/spock-reports#181]
Hi.

First things first. Wanted to say big thanks for this Spock extension, that you've made, as it has saved me and my development team tons of time.

The issue that I wanted to raise however is, that we've run into a case, where we want to generate different bundles of files (as test reports and as documentation) from our Spock test runs.

Something like this:
```
runTest() // one time
├── generateReport() // configured with .html templates
└── generateReport() // configured with .md templates
```

I probably could configure Gradle to run the test task with different configuration parameters, but I don't want to run the same test 2+ times just to get 2 bundles of report/documentation files. I want to run the tests once and have the report generating logic ran 2+ time (each time with different template configuration), while using the same test result.

Is there some way to configure this behavior right now, maybe with Spock configuration? Haven't dug so deep into Spock configuration before. Or will there be a need to extend this extension to account for this scenario?

Thanks in advance. :)

**Comment by yeugenius** [comment]
If you add two IReportCreator classes in spock config (~/.spock/SpockConfig.groovy), it should generate your separate report files for each one.
```
spockReports {
    set 'com.athaydes.spockframework.report.IReportCreator': 'com.athaydes.spockframework.report.template.TemplateReportCreator,com.athaydes.spockframework.report.internal.HtmlReportCreator'
}
```

**Comment by renatoathaydes** [comment]
As @yeugenius said, this is already supported.

It's documented in the README: https://github.com/renatoathaydes/spock-reports#default-properties-values

```properties
# Name of the implementation class(es) of report creator(s) to enable (separate multiple entries with commas)
# Currently supported classes are:
#   1. com.athaydes.spockframework.report.internal.HtmlReportCreator
#   2. com.athaydes.spockframework.report.template.TemplateReportCreator
com.athaydes.spockframework.report.IReportCreator=com.athaydes.spockframework.report.internal.HtmlReportCreator
```

**Comment by treyturner** [comment]
Is it possible to utilize more than one `TemplateReportCreator` though? I'd like to use `geb-spock-reports` for HTML and AsciiDoctor to generate a PDF, but they both want to make use of `TemplateReportCreator`.

**Comment by renatoathaydes** [comment]
Not really, as you wouldn't be able to configure two different templates... but you could work around that by creating a simple class that just extends `TemplateReportCreator` so you could configure it separately.
