### ISSUE TITLE
HtmlReportCreatorSpec doesn't load Spock config properly

### ISSUE THREAD

**Issue by yeugenius** [renatoathaydes/spock-reports#184]
Got build failure when running Gradle build. Checked on both master and next branches on clean checkout.

```
com.athaydes.spockframework.report.internal.HtmlReportCreatorSpec > A correct HTML report is generated for a Specification including extra information added dynamically FAILED
    Condition not satisfied:

    reportFile.exists()
    |          |
    |          false
    /Users/eugene/Documents/projects/spock-reports/build/spock-reports/com.athaydes.spockframework.report.SpecIncludingExtraInfo.html
        at com.athaydes.spockframework.report.internal.HtmlReportCreatorSpec.A correct HTML report is generated for a Specification including extra information added dynamically(HtmlReportCreatorSpec.groovy:291)
```
[spock_test_failure.txt](https://github.com/renatoathaydes/spock-reports/files/3958415/spock_test_failure.txt)

**Comment by yeugenius** [comment]
I'h found what caused this issue. I had active Spock config file in ~/.spock folder, so it broke outputDir path in tests.

```
spockReports {
    set 'com.athaydes.spockframework.report.showCodeBlocks': true
    set 'com.athaydes.spockframework.report.outputDir': 'target/spock-reports'
}
```

**Comment by renatoathaydes** [comment]
Hi @yeugenius .
spock-reports doesn't read the `SpockConfig` file, it's Spock itself that does that.
I'm afraid we can't fix this is spock-reports. Can you maybe raise the problem with the spock-framework project?
