### ISSUE TITLE
Breaking up blocks inside Groovy's with(Closure) method

### ISSUE THREAD

**Issue by treyturner** [renatoathaydes/spock-reports#185]
Hi there; thanks for your work on this project. Is there a way to get `spock-reports` to break up BDD blocks inside Groovy's [`with(Closure)`](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/Object.html#with(groovy.lang.Closure)) method? It's incredibly useful for drying up specs with deeply nested page objects, but causes the BDD blocks to run together in reports:

![image](https://user-images.githubusercontent.com/1878152/71490205-4a927280-27ef-11ea-8b88-0bebfb77667d.png)

I understand associating the `with` line with the following expect block may be too much to ask; I'd happily settle for it living at the bottom of the former block if I could get the blocks nested _within_ the `with` closure split up. In a most ideal state, this would work even when nesting:

```
    def "The 'Preventative Maintenance' toolbar should validate"() {
        given: "the user is on the 'Preventative Maintenance' screen"
        at PreventativeMaintenance

        with(toolbar) {
            expect: "the header should validate"
            header.isDisplayed()

            with(filterControls) {
                and: "the filter controls should validate"
                toggle.isDisplayed()
            }
        }
    }
```

**Comment by renatoathaydes** [comment]
Hi, this is a feature that spock-reports cannot implement. The Groovy AST that parses the BDD blocks is located in the Spock Framework project itself (spock-reports receives the parsed blocks from Spock), so you need to request this feature with the Spock project.
