### ISSUE TITLE
Code block text not shown in report for spec files in sub directory of testSourceRoot

### ISSUE THREAD

**Issue by nj1830** [renatoathaydes/spock-reports#186]
Hi,

In my properties file I have configured the testSourceRoot as follows (basically the default setup)

# Set the root location of the Spock test source code (only used if showCodeBlocks is 'true')
com.athaydes.spockframework.report.testSourceRoots=src/test/groovy

When I locate my spec file under src/test/groovy , the report shows the code block text (when blabla , then blabla, ...)

However when I place the same spec file in location src/test/groovy/subdirectory/...

and rerun the test , the code block text isn't shown anymore in the report.

and I get following log

[Test worker] WARN com.athaydes.spockframework.report.vivid.VividAstInspector - Cannot find source code for spec TemplateManagementSpec
[Test worker] INFO com.athaydes.spockframework.report.vivid.VividAstInspector - Perhaps you need to set the 'com.athaydes.spockframework.report.testSourceRoots' property? (the default is src/test/groovy)

I would expect that all spec files are found in root location even when in subdirectory of root. 

kind regards 

Nico

**Comment by renatoathaydes** [comment]
Did you set the package of the groovy file appropriately?
If the test source root is `src/test/groovy` and you put your Groovy spec in `src/test/groovy/subdir`, then the Groovy file needs to specify its package as `subdir`:

```groovy
package subdir

class MySpec extends Specification {
...
}
```
