### ISSUE TITLE
Add more statistics

### ISSUE THREAD

**Issue by tilmanginzel** [renatoathaydes/spock-reports#193]
Hey,

I was wondering if we could a few more statistics for the report generation (see https://github.com/AOEpeople/geb-spock-reports/issues/17). Below I list all currently available statistics, and the ones which could be added:

**Summary Report:**

- Currently available:
  - Total Specifications
  - Passed Specifications
  - Failed Specifications
  - Specification Success Rate
  - Total Feature Failures
  - Total Feature Errors
  - Total Execution Time
- Missing:
  - Ignored Specifications
  - Total Features Passed
  - Total Features Success Rate

**Specification Report:**

- Currently available:
  - Feature Failures
  - Feature Errors
  - Features Skipped
  - Total Runs
  - Total Features
  - Success Rate
  - Execution Time
- Missing:
  - Passed Features

What do you think? Maybe I could try to provide a pull request for this if you want.

Cheers :)

**Comment by renatoathaydes** [comment]
Hm, aren't all the missing statistics derived from the existing ones?

**Comment by tilmanginzel** [comment]
Yes, I think all of them can be simply derived one way or another. It just seems cleaner to have them directly available in the `Utils.stats` and `Utils.aggregateStats` methods.

**Comment by renatoathaydes** [comment]
We're currently trying to fix the problem with skipped features (or feature iterations) not being shown properly in #191. I will try to add these as we get that fixed.

**Comment by tilmanginzel** [comment]
Sounds good, thanks! I was already wondering if that pull request might be related, I will continue to keep an eye on it.

**Comment by ShubhenduPandey** [comment]
Hi @renatoathaydes 
By making below changes in "Map aggregateStats" I was able to achieve total feature run count and total pass 
**Screenshot of before and after a code change** 
![Screenshot](https://user-images.githubusercontent.com/61691298/92310738-ca9fe780-efce-11ea-9501-8180ed58dbbe.png)
**Report Screenshot**
![report screenshot](https://user-images.githubusercontent.com/61691298/92310820-7b0deb80-efcf-11ea-9e74-dae4111b6c45.png)

Can you please make changes to the code, Our requirement is to show the total feature and total pass/fail count
I was not able to override your method and use it my project, So I guess I have to wait till you make the changes.

**Comment by renatoathaydes** [comment]
@ShubhenduPandey you seem to be misunderstanding what the reports show.

`Total` in the specifications summary report is the total number of specifications, not features.

`Passed` refers to the number of specifications that passed, not features.

Each specification has a feature report, where you can find details about the features.

As far as I can see, this is unrelated to this ticket anyway, please create a new ticket if you still feel like something should be added/changed in the existing reports.

**Comment by ShubhenduPandey** [comment]
I was hoping report to look something like below 
![screenshot16_06_39](https://user-images.githubusercontent.com/61691298/92718676-bf0e4100-f37f-11ea-9e5a-7833a0fb0225.png)

**Comment by renatoathaydes** [comment]
@ShubhenduPandey you can provide [custom CSS files](https://github.com/renatoathaydes/spock-reports#customizing-the-report-stylesheets) to make the report look like this. To change the actual data in the reports, you can create your own [template](https://github.com/renatoathaydes/spock-reports#using-template-reports).

**Comment by renatoathaydes** [comment]
I've decided to just add all statistics requested in the issue's description.

Please have a look at the modified reports I am thinking of releasing soon, which include some of the new stats:

[Specs summary report](https://codepen.io/renatoathaydes/pen/mKckz)

[Spec features report](https://codepen.io/renatoathaydes/full/ihGgt)

**Comment by tilmanginzel** [comment]
Thanks @renatoathaydes, looks good to me. 👍

**Comment by renatoathaydes** [comment]
Finally, this has been fixed in version 1.8.0!!

Please look at the README page on branch `1.7.x` for the updated docs while I don't release again with the `master` branch, while it's at the 2.0-RC version.

**Comment by tilmanginzel** [comment]
Awesome, thank you. :)
