### ISSUE TITLE
Request to provide spec template in html format

### ISSUE THREAD

**Issue by ShubhenduPandey** [renatoathaydes/spock-reports#196]
Hi 
@renatoathaydes 
Great work, Loved Spock report
Can you please provide the summary and spec template in html format if possible. MD format doesn't suit the requirement.
My objective is to calculate the sum of the feature's using jquery which Spock report doesn't provide out of the box as of now https://github.com/renatoathaydes/spock-reports/issues/193
Thanks in advance.

**Comment by renatoathaydes** [comment]
There's no html template currently.

As far as I know, the only templates available are [on the wiki](https://github.com/renatoathaydes/spock-reports/wiki).

Maybe if you check the [feature report](https://codepen.io/renatoathaydes/full/ihGgt) and [summary report](https://codepen.io/renatoathaydes/full/mKckz) models used for testing and design, you could more or less easily adapt them to be used as actual templates?! If you do so, don't forget to add the templates to the Wiki for others to benefit as well!


Cheers.
