### ISSUE TITLE
feature issue annotation

### ISSUE THREAD

**Issue by gorru** [renatoathaydes/spock-reports#198]
Hi.
There is some way to access the feature issue annotation and show it in a custom report?
Thanks in advance.

**Comment by renatoathaydes** [comment]
I believe `@Issue` annotations are given by spec's `Tags. The default MD template report does this:

```groovy
def writeTagOrAttachment = { feature ->
    def tagsByKey = feature.tags.groupBy( { t -> t.key } )
    tagsByKey.each { key, values ->
        out << '\n#### ' << key.capitalize() << 's:\n\n'
        values.each { tag ->
            out << '* ' << tag.url << '\n'
        }
    }
    if ( feature.attachments.size > 0 ) {
        out << '\n#### ' << 'See:' << '\n\n'
        feature.attachments.each { value ->
            out << '* ' << value.url << '\n'
        } 
    }
}

writeTagOrAttachment data.info
```

As you can see [here](https://github.com/renatoathaydes/spock-reports/blob/master/src/main/resources/templateReportCreator/spec-template.md).

**Comment by tilmanginzel** [comment]
I think you can you also use the method [`Utils.featureAnnotation(...)`](https://github.com/AOEpeople/geb-spock-reports/blob/master/src/main/resources/templates/spec-template.html#L40) to easily get any feature annotation. [Example](https://github.com/AOEpeople/geb-spock-reports/blob/master/src/main/resources/templates/spec-template.html#L192) in this [template](https://github.com/AOEpeople/geb-spock-reports/blob/master/src/main/resources/templates/spec-template.html#L40).

**Comment by gorru** [comment]
Thank you. I'll try today

Il gio 22 ott 2020, 00:20 Tilman Ginzel <notifications@github.com> ha
scritto:

**Comment by gorru** [comment]
I solved using a custom function because I'm using the 1.x version of spock
thanks to yours hints

def getFeatureAnnotations = {feature, annotation ->
    def annotations = feature.description.getAnnotation( annotation )?.value()

    if( annotations){
        specIssueId = annotations[0]
    }
}


Thanks a lot!
