### ISSUE TITLE
Spock-2.0-M3+ compatibility

### ISSUE THREAD

**Issue by thokari** [renatoathaydes/spock-reports#200]
Hello,
apparently this constructor signature has changed with version `2.0-M3` of Spock:
https://github.com/spockframework/spock/blob/spock-2.0-M3/spock-core/src/main/java/org/spockframework/runtime/model/IterationInfo.java#L32

This change leads to an exception from this invocation:
https://github.com/renatoathaydes/spock-reports/blob/master/src/main/groovy/com/athaydes/spockframework/report/SpockReportExtension.groovy#L265

This PR might fix it, but I have not tested it yet:
https://github.com/renatoathaydes/spock-reports/pull/199

**Comment by renatoathaydes** [comment]
I have just released Spock-reports `2.0-RC3` with support for Spock `2.0-M4-groovy-3.0`. Let me know if you have any issues.
