### ISSUE TITLE
toggle to turn on report generation on demand

### ISSUE THREAD

**Issue by LionOnTheChase** [renatoathaydes/spock-reports#204]
Hi,

In a monolith project that I'm working on, generation of reports is greatly slowing down the test execution. 

If only there was a way to generate reports only on request by way of a gradle property, that would be great. 

something like using -PenableSpockReport to generate reports would be really great addition. 

report generation could be turned off  by having a property to dictate it.

**Comment by renatoathaydes** [comment]
I am surprised that you found that reports are slowing down your build... can you enable logging as shown in the README page and post the relevant logs you see? Spock-reports usually is quite fast in my experience.

In any case, it's already possible to disable the reports as shown in the README's config file example:

```
com.athaydes.spockframework.report.internal.HtmlReportCreator.enabled=false
```

This is for the default HTML report... if you're using some other custom report creator, just replace the name of the class.

**Comment by renatoathaydes** [comment]
Notice that you can use the Spock Groovy config file as well, as [shown here](https://github.com/renatoathaydes/spock-reports#using-spockconfiggroovy). This would allow you to use a system property, env variable or whatever you prefer to disable/enable reports.
