### ISSUE TITLE
Missing version for junit-jupiter and junit-platform-testkit in 2.0-RC3

### ISSUE THREAD

**Issue by g3force** [renatoathaydes/spock-reports#205]
In the POM of version 2.0-RC3 the versions for junit-jupiter and junit-platform-testkit got removed:
https://repo1.maven.org/maven2/com/athaydes/spock-reports/2.0-RC3/spock-reports-2.0-RC3.pom

In the previous version, they were present:
https://repo1.maven.org/maven2/com/athaydes/spock-reports/2.0-RC2/spock-reports-2.0-RC2.pom

This produces a Warning in Maven when including spock-reports as a dependency:
```
[WARNING] The POM for com.athaydes:spock-reports:jar:2.0-RC3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
The POM for com.athaydes:spock-reports:jar:2.0-RC3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

Is there a reason why those versions got removed?
The build runs fine and produces the report, but the Warning is pretty annoying.

**Comment by pauloedwardo** [comment]
I've got the same issue, but in my case the report isn't produced. The solution was downgrade version to 1.8.0. After that, the reports was produced as well.

Gradle output:
![screenshot_1](https://user-images.githubusercontent.com/6704717/107787775-4f392380-6d2e-11eb-9d2e-c6f5e3be6cd4.png)

**Comment by renatoathaydes** [comment]
I'm sorry about that.

Looks like this change is the problem:

https://github.com/renatoathaydes/spock-reports/pull/203/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R33

I thought using the Gradle BOM support would make things better so I followed [the instructions](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import) and added this:

```groovy
    testImplementation platform('org.junit:junit-bom:5.7.0')
    testImplementation 'org.junit.platform:junit-platform-testkit'
    testImplementation 'org.junit.jupiter:junit-jupiter'
```

I didn't expect that would change the POM.

I am investigating how to get things working again.

**Comment by renatoathaydes** [comment]
@g3force I've created a Maven project and indeed saw the warning.

Luckily, I had to modify the build file again in order to move from JCenter to Maven Central (the project  was being published to Maven Central indirectly, via Bintray) and the newer version seems to work without warnings.

Please try this:

```xml
<dependency>
  <groupId>com.athaydes</groupId>
  <artifactId>spock-reports</artifactId>
  <version>2.0.1-RC3</version>
  <scope>test</scope>
</dependency>
```

@pauloedwardo I've tried in Gradle as well, and the reports were generated as expected.

This is my test Gradle file:

```groovy
plugins {
    id 'groovy'
}
repositories {
    mavenCentral()
}
dependencies {
    // mandatory dependencies for using Spock
    compile "org.codehaus.groovy:groovy:3.0.7"
    testCompile platform("org.spockframework:spock-bom:2.0-M4-groovy-3.0")
    testCompile "org.spockframework:spock-core"

    testCompile 'com.athaydes:spock-reports:2.0.1-RC3'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
```

Let me know if something's still off.

**Comment by g3force** [comment]
Looks good on the Maven side. Thx for the fast reaction :+1:
