### ISSUE TITLE
If you use @ runwith（ PowerMockRunner.class ）The corresponding HTML report cannot be generated

### ISSUE THREAD

**Issue by vichbb** [renatoathaydes/spock-reports#209]
If you use @ runwith（ PowerMockRunner.class ）, the corresponding HTML report cannot be generated on the index page, but the sub page exists.

**Comment by renatoathaydes** [comment]
Does Spock support PowerMock?

**Comment by renatoathaydes** [comment]
Closing this because to my knowledge, Spock specs must be executed via Spock's own JUnit Runner and Spock has its own Mocking capabilities, making the use of PowerMock unsupported. I will change my mind if you can show that Spock indeed has explicit support for this library.
