### ISSUE TITLE
reportInfo doesn't work correctly with spock's parallel execution

### ISSUE THREAD

**Issue by dariuslf** [renatoathaydes/spock-reports#219]
I've recently tried adding extra info to the reports to note which test data has been used. the `reportInfo` exnsion function is great.
However, things didn't work out when configuring spock to run in parallel, eg.

`runner {
    parallel {
        enabled true
        fixed(4)
    }
}`

The info traced with `reportInfo` wasn't necessarily located in the correct feature report!  I could get four features of a single spec starting at the same time and the info traced by each landing all together on one of the features.

**Comment by renatoathaydes** [comment]
Ah parallel builds are being  difficult to get right!

This might be a simple fix, I hope... I will have a look at why this would happen.

**Comment by renatoathaydes** [comment]
The information is collected at [SpockReportsSpecificationExtension](https://github.com/renatoathaydes/spock-reports/blob/master/src/main/groovy/com/athaydes/spockframework/report/extension/SpockReportsSpecificationExtension.groovy#L41). Looks like that will be hard to work in parallel builds!

**Comment by dariuslf** [comment]
Yes, I understand.
Maybe you can use the `specificationContext` property (https://github.com/spockframework/spock/blob/232514b2bf2755968138b52e95fffa98e57764f0/spock-core/src/main/java/org/spockframework/lang/SpecInternals.java#L34) from within your `reportInfo` extension method to get the name of the currently executing feature.
It's marked as `@Beta` so I guess you can decide whether it's appropriate.

**Comment by renatoathaydes** [comment]
Problem is now fixed. Thanks @dariuslf for the heads up on `specificationContext`, that helped a lot!

I had to introduce a breaking change on report templates in order to get this fixed. Please see the commit linked above if anyone has problems with their templates.

**Comment by dariuslf** [comment]
Just wanted to thank you for this.
Looks great!
