### ISSUE TITLE
Unexpected state: running afterSpec without having a specData for

### ISSUE THREAD

**Issue by mikesz14** [renatoathaydes/spock-reports#221]
Hi 

I'm running spock test pack and after each spec I can see:
[Test worker] DEBUG c.a.s.report.SpecInfoListener - Unexpected state: running afterSpec without having a specData for ...

Spring Boot: 2.6.3
Groovy: 3.0.9
Spock: 2.0-groovy-3.0
Spock-reports: 2.2.0-groovy-3.0

I'm not sure but maybe it's due to multiple workers? 4 executors
Report looks OK

**Comment by renatoathaydes** [comment]
Hm yeah that should not normally happen. I will check if there's something wrong when running multiple executors.

**Comment by renatoathaydes** [comment]
This appears to be related to the #222 bug. Luckily it doesn't break reports in all cases, but I will get this fixed as soon as possible.

**Comment by renatoathaydes** [comment]
This issue should've been fixed with #222 in version `2.3.0-groovy-3.0`. Please let me know if you still have any problems.
