### ISSUE TITLE
Generating multiple report formats

### ISSUE THREAD

**Issue by ekozynin** [renatoathaydes/spock-reports#225]
What is the recommendation on generating multiple report formats, for example both HTML (out-of-the-box) and custom JSON reports?

thank you

**Comment by renatoathaydes** [comment]
In the README page, there's a [list of properties](https://github.com/renatoathaydes/spock-reports#default-properties-values) you can use to configure spock-reports, the first of which is:

```properties
# Name of the implementation class(es) of report creator(s) to enable (separate multiple entries with commas)
# Currently supported classes are:
#   1. com.athaydes.spockframework.report.internal.HtmlReportCreator
#   2. com.athaydes.spockframework.report.template.TemplateReportCreator
com.athaydes.spockframework.report.IReportCreator=com.athaydes.spockframework.report.internal.HtmlReportCreator
```

As it says, you can use `,` to use more than one report creator.
