### ISSUE TITLE
Groovy 4 support

### ISSUE THREAD

**Issue by ct-source** [renatoathaydes/spock-reports#234]
Thank you for your awesome work.
Do we have any plan to support groovy 4 ?

**Comment by renatoathaydes** [comment]
Yes! I was waiting for Spock to get some releases out, but looks like they've done that already.
Will keep this ticket updated.

**Comment by renatoathaydes** [comment]
Groovy 4 support is done on the `groovy-4` branch:

https://github.com/renatoathaydes/spock-reports/tree/groovy-4

If anyone could try this to confirm it's working, that would be great.

**Comment by Pedja-P** [comment]
I have tried with groovy 4.0.4, looks good to me. There are no warning messages for invalid property values and default CSS has been applied in report.

**Comment by renatoathaydes** [comment]
Thanks @Pedja-P for confirming. I got a couple other devs also confirming the groovy-4 branch is good to go... I am going to wait for a PR fixing a last ticket before I release a new version for Groovy 3, and then finally, a Groovy 4 version!

**Comment by renatoathaydes** [comment]
Done! Version 2.4.0-groovy-4.0.
