### ISSUE TITLE
Integrate GEB screenshots as part of the Spock-Reports feature

### ISSUE THREAD

**Issue by DaniP13** [renatoathaydes/spock-reports#243]
This has been a very powerful feature that added value to Spock and Geb **BUT** since https://github.com/AOEpeople/geb-spock-reports is not maintained anymore maybe a good idea will be to integrate it into this as a whole or add the possibility to display screenshots that GEB already provides into the current format or maybe just a link to point them :)

We all really appreciate the entire work that has been done so far and we hope for a minimum maintenance.

Regards

**Comment by renatoathaydes** [comment]
I still maintain this project but do not use Geb (at least not with spock-reports). It would be too hard for me to maintain that. If someone else wants to do it, I can help and link to their project.

**Comment by DaniP13** [comment]
Thanks @renatoathaydes for your quick reply. We know and we do appreciate that this project is still maintained giving the fact that other projects were abandoned, is is a great thing to see that you still provide updates for this one. 
The proposal was like a fusion between this project and that one mentioned above, having like a feature if you want the possibility to activate\deactivate this GEB report. 

Now that you disagree with this suggestion, we (more people who uses this project are interested) want to know if there is any chance in the future to have a feature like screenshots integrated with this? - this will have a huge positive impact over spock-reports project. 

We all appreciate the effort and looking forward for your reply. 

Best regards,

**Comment by renatoathaydes** [comment]
Hi @DaniP13 . Just to clarify this question: spock-reports is a generic JVM testing framework report extension, it simply doesn't even have the concept of "screens" let alone "screenshots". Those things can be added to reports with current methods to extend spock-reports, including template reports but also by programmatically generating and adding information to the report, [see this](https://github.com/renatoathaydes/spock-reports#adding-information-to-reports-programmatically).

It's not only that I don't want to maintain such feature: it doesn't make sense at all to add it directly to spock-reports.
The way the GEB extension was managed is the correct way to add these features. All you need to do is fork that project and keep maintaining it in the future... I can help if you have any doubts on how it works, but I won't be willing to fork that project myself.

If you decide to fork the project, let me know so I can update the link to the GEB extension to point to your project.
