### ISSUE TITLE
Feature Request: Report Templates

### ISSUE THREAD

**Issue by rdmueller** [renatoathaydes/spock-reports#28]
> Finally, I can definitely create a template mechanism for spock-reports. Please make a feature request as well!

Hope this is the right place for such a request :-)

The spock-reports project is the best spock report I am aware of (besides the Spock V1.0 reports :-), but it would be even more flexible, if the core would collect the report data as model and feed it into a (HTML) template. This way, everybody could easily modify the template and add to it without breaking the reports for other users. 

IMHO, one of the template engines already provided by Groovy would be a good start http://groovy.codehaus.org/Groovy+Templates .

**Comment by renatoathaydes** [comment]
I love this! Will attack this ASAP!

**Comment by rdmueller** [comment]
tell me if I can be of any help!

**Comment by renatoathaydes** [comment]
The basic template is implemented (in the `next` branch). I still need to create the aggregate report with links to the feature reports, but that should be pretty simple.
I have documented templates in the README.

Feedback welcome.

**Comment by rdmueller** [comment]
great! I will give it a try asap.

**Comment by renatoathaydes** [comment]
I think this is ready for release now!

**Comment by rdmueller** [comment]
ok. so if you think it is ready, this would make testing on my side even easier... then I will give it a try as soon as it is released.

**Comment by renatoathaydes** [comment]
This feature is released in version 1.2.5!
