### ISSUE TITLE
Enhancement: Debug-Mode

### ISSUE THREAD

**Issue by rdmueller** [renatoathaydes/spock-reports#36]
Now that we can specify some properties as environment variables, some kind of loglevel=debug would be helpful, because spock-reports too often fails silent.

I the log-output, I would like to see
- the classpath where the plugin looks for a properties file
- in case of the template report generator, the absolute path + filename the generator expects the templates to be if it gets a file not found

**Comment by renatoathaydes** [comment]
We're using `java.util` logging now... have you tried enabling `FINEST` level?

I think you can do it like this:

```java
LogManager.getLogManager().getLogger(Logger.GLOBAL_LOGGER_NAME).setLevel(Level.FINEST);
```

**Comment by rdmueller** [comment]
maybe it's just me, but
- it's not too easy to activate the logger this way
- as far as I remember the code, thsi would not solve my problem (where does the plugin look for configuration files)

For me, a big obstacle is always to find where the plugin is looking for the configuration and I wonder how this problem could be solved...

**Comment by renatoathaydes** [comment]
I agree that we should show which files spock-reports tried to use if something goes wrong... I can try to do that (even though it's not a single place it will look at, it is anywhere in the classpath).

I was just asking if you've got some useful debug messages when you enable `java.util.logging`?

You don't need to enable it programmatically, you can edit the config file for logging.

Give the config file as a parameter to the JVM:

```
-Djava.util.logging.config.file=/path/to/app.properties
```

**Comment by rdmueller** [comment]
does not work somehow. I have no experience with java.util.logging. I've set the location of the config file by starting gradle with 

    gradle -Djava.util.logging.config.file=/path/to/app.properties myTask

and could verify that this system property was set. I created a properties file like this

    handlers= java.util.logging.ConsoleHandler
    .level= ALL
    com.athaydes.spockframework.report.template.level=ALL
    com.athaydes.spockframework.report.level=ALL

but nothing happened. Any Idea?

**Comment by rdmueller** [comment]
update: at least I have a solution - when I run the test inside my IDE (IntelliJ), I get the log messages on the console

**Comment by rdmueller** [comment]
that's great! thanx!
