### ISSUE TITLE
enhancement: @Narrative & @Title

### ISSUE THREAD

**Issue by rdmueller** [renatoathaydes/spock-reports#37]
Spock supports the two annotations @Narrative and @Title for better documentation of our tests (see http://spockframework.github.io/spock/docs/1.0/extensions.html for details).

Would it be possible to access the text gathered by these annotations from within the reports?

**Comment by renatoathaydes** [comment]
Pretty easy to do.

For example, in a spec template, this will work if the Specification is annotated with ``@Narrative`` (at least with Spock 1.0+):

```groovy
The narrative is: ${data.info.narrative}
```
I could not find where `@Title` is stored... I had thought `${data.info.description.displayName}` would've worked, but it didn't (it just returns the class name).

But you can get the class of the Specification like this:

```groovy
Class type = data.info.description.testClass
```
Now, you can just use `Class` to get annotations and their values:

```groovy
Title is ${(data.info.description.testClass.getAnnotation( spock.lang.Title )?.value() ?: 'NOT FOUND')}
```

**Comment by rdmueller** [comment]
the @Narrative works - since they both annotate the class, I guess I don't need the @Title, do I?

Thanx!

**Comment by renatoathaydes** [comment]
Cool! I will add support for it in the standard HTML reports. Thanks for letting me know about that :)
