### ISSUE TITLE
Skipped features count reporting the total feature method count

### ISSUE THREAD

**Issue by sophosis** [renatoathaydes/spock-reports#38]
Total 15 feature methods in EditorSpecification (Stepwise).

```
Name                Features    Failed  Errors  Skipped Success rate    Time
EditorSpecification 6           0       1       15      83.33%          1 minutes, 7.294 second
```

The success rate I'm unsure about, also... looks like (6-1)/6 for this example? This may be by design, but are skipped methods not considered in the success rate?

**Comment by renatoathaydes** [comment]
You are correct, skipped features are not counted in the success rate. Are you asking for us to count them as success or failures, or something else?

**Comment by sophosis** [comment]
Well, in the example I included.. there were 15 total feature methods. 6 ran and 1 failed. Since it's a Stepwise spec, the rest were skipped (should be 8 skipped, but is showing the total feature method count, instead). Even though only 5 of the 15 passed, success rate is showing as 83.33%.

After thinking about it some more, it may just be that in my use case, skipped makes more sense when counted as failures. But, I can see it making more sense to not include them on the failure, or success, side of the computation for the more general case, as is currently done.

So, that just leaves the question of the Skipped feature method count showing the total feature method count instead of actual skipped.

**Comment by renatoathaydes** [comment]
We have improved statistics a few times since this ticket was opened, including today's 1.8.0 release which added new statistics (see #193). Closing issue as this should've been solved for some time now.
