### ISSUE TITLE
Enhancement: Add "Failures due to Issue" column into Summary

### ISSUE THREAD

**Issue by rasimsitmanbetov** [renatoathaydes/spock-reports#40]
It will be nice to see a number of failed tests, which are probably already known and thus has @Issue annotation with e.g. link to issue in some bug tracker.

This could be a column "Failures due to issue" in a Summary table, which refers to a value containing a number of failed tests due to known issues (with @Issue) ${failures}

**Comment by renatoathaydes** [comment]
Done in 1.2.6. Please try it out!
