### ISSUE TITLE
Enhancement: Apply different style for failed tests with @Issue

### ISSUE THREAD

**Issue by rasimsitmanbetov** [renatoathaydes/spock-reports#41]
This could be really nice to have a possibility to single out failed tests with @Issue from 
failed tests not being annotated with @Issue.

For this:
1. Add new style for failed tests with @Issue, e.g. *feature-toc-failure-with-issue* or *feature-toc-issue* **and**
*feature-description.failure-with-issue* or *feature-description.issue* 
2. In default template apply some different color for new style, e.g. yellow #FFFF33

**Comment by renatoathaydes** [comment]
Please check the [new design](http://codepen.io/renatoathaydes/full/ihGgt) which adds support for the @Issue annotation, as per issue #39.

The style class "issues" is added to the div where the issues are shown. You can easily use your own stylesheet to modify the styles if you're not happy with the default stylesheet, as explained in the README page.

Hope the above is enough for closing this ticket. Let me know what you think.

**Comment by rasimsitmanbetov** [comment]
I've checked the new design and it is exactly what was requested! Thank you!
