### ISSUE TITLE
Bug - "Return" hyper links on feature descriptions don't work

### ISSUE THREAD

**Issue by Kenster69** [renatoathaydes/spock-reports#42]
There is a "Return" hyperlink embedded in the description of each feature on the right hand side, which ( I assume ) should take you back to the "Summary" or "Features" section at the top of the page.

![image](https://cloud.githubusercontent.com/assets/12425242/7606190/88cd27f4-f94e-11e4-8af1-f70bb46e2b63.png)

However, this has not been set up anywhere, so clicking on the link does not do anything.

Can this be fixed?

**Comment by renatoathaydes** [comment]
@Slugger  can you check this out?

**Comment by renatoathaydes** [comment]
@Kenster69  can you post the HTML contents of the ToC and of some Return links?

**Comment by Slugger** [comment]
Yeah, going to need to see the generated html to properly investigate.

**Comment by Kenster69** [comment]
Hi,
When I cut and paste HTML in here, it gets rendered as html. So I am attaching screenshots of relevant info.
Am happy to email a file with the html if you give me an address to send to.


Regards,
Kenny

![toc](https://cloud.githubusercontent.com/assets/12425242/7634160/ec4fcf7c-fa50-11e4-98dd-8ee20f9dc2b3.png)

![sr2](https://cloud.githubusercontent.com/assets/12425242/7634174/016a60de-fa51-11e4-97c8-72b4b72617a5.png)

![sr3](https://cloud.githubusercontent.com/assets/12425242/7634177/06a957d0-fa51-11e4-87dd-f9debcb51026.png)

**Comment by Slugger** [comment]
The html looks right.  The id for the `<ul>` is correct and the links look fine.  Browsers may appear to do nothing if the `<ul>` is already on screen and you click a return link (i.e. if the `<ul>` is already visible the browser may choose to ignore the click).  The real test is to ensure there are enough items such that you can scroll down some so the TOC is off screen.  In that case, clicking any return link should then return you to the TOC.

If you've tried this and it's still not working, which browser(s) is it not working in?  I see IE in the orig screenshot.  Which version of IE is that?  Did you try in other browsers (Chrome, FF)?

**Comment by Kenster69** [comment]
Hi,
I thought that might have been the case, but I added in enough cases to make the TOC off the screen - but still no joy.

I am using IE version 9.0.8112.16421

However, I did try it on Chrome and it is working!

**Comment by Slugger** [comment]
It's not like we're even using js or anything fancy like that for this stuff.  IE9 is old (real old).  Still I'm surprised (but not shocked) that it doesn't work in IE9.  I just tested using IE10 and it works as expected.  I'll assume IE11 is the same (99% sure I tested on some vm with IE11 on it when I wrote it).  Therefore I say close this bug as "works for me/unsupported browser".

**Comment by Kenster69** [comment]
Happy with that, thanks for looking.
