### ISSUE TITLE
spock-reports index.html incomplete when running in parallel

### ISSUE THREAD

**Issue by treyturner** [renatoathaydes/spock-reports#43]
Hello,
Thanks for your work on spock-reports. I'm seeing something strange that may very well be a configuration issue on my side, but I think this is the right place to ask.

I'm running spock-core:1.0-groovy-2.4 and spock-reports:1.2.5 via gradle, attempting to execute my specs in parallel. It seems that all of the per-spec spock-reports are being generated (ie. com.example.package.TestSpec.html), but the main index.html generated only contains one thread worth of results in summary. Is there a way to get the cumulative result of all threads put into spock-reports' index.html?

By comparison, the index.html contained in the reports generated by Spock itself seems to report comprehensive results across all threads.

Thanks,
Trey

**Comment by renatoathaydes** [comment]
Hi!

Sorry, we cannot support parallel builds for now.
We hope to fix this in a release in the near future!

**Comment by renatoathaydes** [comment]
This is obviously an essential feature, everyone should be using parallel test execution! Will make an effort to include this already in the next release, 1.2.6.

**Comment by renatoathaydes** [comment]
Parallel builds are currently supported in branch `issue-39`. I would really appreciate anyone who can try it with some large parallel builds in Windows and Mac (I've done it in Linux)!! Please let me know if you can do it.

Hope to release it as soon as I know it works in a few OS's... this is because this feature relies on [FileLock](http://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileLock.html), which may present different behaviour depending on the OS, unfortunately.

**Comment by treyturner** [comment]
I would be happy to test this if you could explain to me how I could implement the branch version into my Gradle build. Right now I'm implementing via Maven dependency in my build.gradle. If this is too much trouble, I'll patiently wait for the feature to be merged.

Thanks again for looking at this; the timing is perfect because the default Spock reports stopped generating for me a while ago and I haven't been able to figure out why. :worried:

**Comment by renatoathaydes** [comment]
To test this, you just need to clone this repo in your local machine, build it, then publish the artifacts to your local Maven repo.

Here's how to do it:

```
git clone git@github.com:renatoathaydes/spock-reports.git
cd spock-reports
bash ./gradlew clean publishToMavenLocal
```

You can then change the spock-reports version in your own project's Gradle script to be the version you've just built (now it is `1.2.6-SNAPSHOT`).

If you have trouble, run the builld with the `--info` option or `--stacktrace`:

```
gradle clean test --info
```

**Comment by treyturner** [comment]
I just wanted to note that this process and the code update worked great for me on OSX 10.10. We don't do things massively in parallel at my shop, but I was able to have the result of about 40 tests all dump to the index.html from four different threads.

I thought I'd be able to test on Linux, but getting the snapshot artifact into a repo that that machine can access isn't going to be possible. Thanks again for your help and I look forward to this feature being merged.

**Comment by renatoathaydes** [comment]
Thank you! I've already tested linux. Will try to test on Windows myself later (I have Windows in my laptop but haven't used it for over an year!) before releasing.

**Comment by renatoathaydes** [comment]
Confirmed the fix works in Windows! Took me a long time because I hadn't turned on the Windows laptop in years, so it was hard to get it working/building/updated.
Will release as soon as Windows stops updating stuff and my backups are finished!
