### ISSUE TITLE
Could not create custom template report - geting a runtime error "Template File does not exist: "

### ISSUE THREAD

**Issue by rameshnatesan** [renatoathaydes/spock-reports#44]
Hi Renato Athaydes,

Thank you for this Spock Reports Extension project, I really like it. I followed your instructions in your "ReadMe.md" for creating my own "spec-template.md" and "summary-template.md" to create reports using TemplateReportCreator.

These two .md files are in src/test/resources folder in my gradle project. I have configure gradle, geb, spock, spock-reports and others related dependencies for running the spock tests.

I have the following content in the META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties file.

#************************
com.athaydes.spockframework.report.IReportCreator=com.athaydes.spockframework.report.template.TemplateReportCreator

com.athaydes.spockframework.report.template.TemplateReportCreator.specTemplateFile=templateReportCreator/spec-template.md
com.athaydes.spockframework.report.template.TemplateReportCreator.reportFileExtension=md
com.athaydes.spockframework.report.template.TemplateReportCreator.summaryTemplateFile=templateReportCreator/summary-template.md
com.athaydes.spockframework.report.template.TemplateReportCreator.summaryFileName=summary.md
com.athaydes.spockframework.report.outputDir=build/custom-spock-report

com.athaydes.spockframework.report.hideEmptyBlocks=false
#************************

After running a test, it creates a empty folder in build named "custom-spock-report". I am getting an error messages that says:
"org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke WARNING: Unexpected error creating report: java.lang.RuntimeException: Template File does not exist: src/test/resources/spec-template.md".

I tried both "src/test/resources/spec-template.md" and "/src/test/resources/summary-template.md" but it could not the .md paths in both cases. It says file does not exist.

Can you please provide some help on this setup?

Thank you
Ram

**Comment by rameshnatesan** [comment]
I moved the .md template files under the default package.
after I ran the test I get this message in the build/reports/

org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
WARNING: Unexpected error creating report: groovy.lang.MissingMethodException: No signature of method: groovy.tmp.templates.GStringTemplateScript1$_getTemplate_closure1$_closure2.doCall() is applicable for argument types: (java.lang.String, com.athaydes.spockframework.report.template.TemplateReportCreator$_createFeaturesCallback_closure1) values: [forEach, com.athaydes.spockframework.report.template.TemplateReportCreator$_createFeaturesCallback_closure1@67055344]
Possible solutions: findAll(), findAll(), doCall(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)

**Comment by rdmueller** [comment]
this example gradle project might help you: https://github.com/rdmueller/etka15/tree/master/src/test/resources

it's a bit more complex because it creates an asciidoc templates with geb screenshots, but I guess you'll be able to find oyur problem by comparing the sources/configuration of the spock-reports plugin.

**Comment by renatoathaydes** [comment]
The path to the template file, as the README page explains, is relative to the java classpath. This means that if you put your file in `src/test/resources/templateReportCreator/summary-template.md` (and you're using Gradle or Maven), then, because `src/test/resources/` is part of the test classpath, you should declare the path to the file as `/templateReportCreator/summary-template.md`.

Regarding the other error you got, I agree with @rdmueller, please compare with a working project and see what you're doing different.

**Comment by rameshnatesan** [comment]
Thanks, I followed the folder structure as in the etka15 project. But I am seeing an empty build/spock-reports-ad folder created. can you please tell me where I should see the report file after running a test?

After running the test I opened the html in the path /build/reports/phantomJsTest/tests/classes/GebishOrgSpec.html and the standar error shows this same error again:


org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
WARNING: Unexpected error creating report: groovy.lang.MissingMethodException: No signature of method: groovy.tmp.templates.GStringTemplateScript1$_getTemplate_closure1$_closure2.doCall() is applicable for argument types: (java.lang.String, com.athaydes.spockframework.report.template.TemplateReportCreator$_createFeaturesCallback_closure1) values: [forEach, com.athaydes.spockframework.report.template.TemplateReportCreator$_createFeaturesCallback_closure1@413c5218]
Possible solutions: findAll(), findAll(), doCall(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)

I even ran the etka15 project with phantomJsTest as task. I am note sure where it created the report.

**Comment by rdmueller** [comment]
the etka15 project will generate two .ad files in etka15\build\spock-reports-ad

Maybe you are searching in the wrong spot: you will also end up with an empty folder if the template contains an error. Try to put some debug println statements in you templates.

Maybe you can put your template somewhere that we can have a look at it?

**Comment by rameshnatesan** [comment]
I just ran with a println line and also with few other lines and it did create md files in spock-reports folder.

**Comment by rameshnatesan** [comment]
there is a line that has forEach in the spec-template.md.

This forEach method is not recognized during test run Error is org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
WARNING: Unexpected error creating report: groovy.lang.MissingMethodException: No signature of method: groovy.tmp.templates.GStringTemplateScript1$_getTemplate_closure1$_closure2.doCall() is applicable for argument types: (org.spockframework.runtime.model.FeatureInfo) values: [org.spockframework.runtime.model.FeatureInfo@6bb3c35a]
Possible solutions: findAll(), findAll(), isCase(java.lang.Object), doCall(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object), isCase(java.lang.Object)


My spec-template.md file has this same as in spock-report example spec-template.md file


## Features
<%
    features.forEach { name, result, blocks, iterations, params ->
%>
### $name

**Comment by rameshnatesan** [comment]
My spec-template.md file has the following :

<%  def fmt = new com.athaydes.spockframework.report.internal.StringFormatHelper()
    def stats = com.athaydes.spockframework.report.util.Utils.stats( data )
 %># Report for ${data.info.description.className}

##Summary

* Total Runs: ${stats.totalRuns}
* Success Rate: ${fmt.toPercentage(stats.successRate)}
* Failures: ${stats.failures}
* Errors:   ${stats.errors}
* Skipped:  ${stats.skipped}
* Total time: ${fmt.toTimeDuration(stats.time)}

<%
    features.forEach { name, result, blocks, iterations, params ->
%>
Feature Name: $name
Result: $result
<%
    }
%>



When using this spec template I am getting te following error. Do I need to import something or define a def variable? This forEach is not working although I copied the exact code block from the readme https://github.com/renatoathaydes/spock-reports.


WARNING: Unexpected error creating report: groovy.lang.MissingMethodException: No signature of method: groovy.tmp.templates.GStringTemplateScript1$_getTemplate_closure1$_closure2.doCall() is applicable for argument types: (java.lang.String, com.athaydes.spockframework.report.template.TemplateReportCreator$_createFeaturesCallback_closure1) values: [forEach, com.athaydes.spockframework.report.template.TemplateReportCreator$_createFeaturesCallback_closure1@77a5d813]
Possible solutions: findAll(), findAll(), doCall(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object)

**Comment by rdmueller** [comment]
It's not easy to debug those templates. The best way to figure out what's going wrong is to wrap the part of the templates in which you expect the Problem in a try/catch block and println the stacktrace. At least it helped me a lot...

**Comment by renatoathaydes** [comment]
`forEach` does not exist in Groovy, it should be `each`.

```groovy
<%
features.each { name, result, blocks, iterations, params ->
%>
```

**Comment by renatoathaydes** [comment]
Oops... ignore my comment above! The `forEach` in this case is actually right, it's not the built-in Groovy `each` (I remember naming if `forEach` to make sure Groovy did not confuse it with `each`!!).

**Comment by renatoathaydes** [comment]
I cannot see why this `forEach` would be the problem. Can you run gradle with the ``--stacktrace`` option and post the full stack-trace?

**Comment by rdmueller** [comment]
did some tests with my etka15 project and was surprised to get no output and no error message.
though about what I changed since the last successfull run... the JDK! :-(

So if I run my project with jdk8, I get an empty spock-reports folder. With JDK7, everything seems to be ok.

If I copy your spec template into my project, everything's fine, too! Your template works (at least with my project and JDK7).

Can you please check which JDK you use and what happens if you change it?

**Comment by rdmueller** [comment]
@renatoathaydes : it seems that JDK8 has a problem with the forEach in the template. But even if I remove it from the template, I get a problem with the forEach contained in the `TemplateReportCreator`:

https://github.com/renatoathaydes/spock-reports/blob/f8e4c0ac8d6d77efc2e70c19a4b0bad932899267/src/main/groovy/com/athaydes/spockframework/report/template/TemplateReportCreator.groovy#L69

**Comment by rameshnatesan** [comment]
I have jdk 8. Let me try with jdk 7 and see if it works.

**Comment by rameshnatesan** [comment]
it works fine in jdk 7.
if I use jdk 8, what should I use instead of forEach?

I think even the each is nor working using jdk 8

**Comment by rdmueller** [comment]
As far as I can see, this can't be fixed with only a change in the templates. Either the Plugin has to be changed too (it also contains a forEach) or the groovy Version has to be updates.
I'm not sure, but maybe a newer groovy Version can be used without changing the Plugin...?

**Comment by renatoathaydes** [comment]
Oh, this is surprising... you can change your Groovy version, the spock-reports plugin does not demand a particular Groovy version (it just has to be 2.0+). This may actually be that your Groovy version does not support Java 8? Please try [Groovy 2.3](http://www.groovy-lang.org/releasenotes/groovy-2.3.html) and above.

**Comment by rameshnatesan** [comment]
I already have groovy 2.+
Still getting error

**Comment by renatoathaydes** [comment]
2.3+ ?

**Comment by rameshnatesan** [comment]
Hi Renato,
Yes I tried with ver 2.3.4 and it did not work.
I read about this article that groovy does not really support  Java 8 until
groovy version 4.
http://www.infoworld.com/article/2608199/java/one-now--two-later--groovy-updates-add-java-8-support.html

Can you please change forEach to each or other jdk 7 friendly method in the
next spock reports version?

Thank you

**Comment by renatoathaydes** [comment]
Version 1.2.6 has just been released. It was tested with Java 8 and works as expected.

The `forEach` method was renamed to `eachFeature`.

@rameshnatesan  Please test this on your end if you can, and close the ticket if you're happy.

Thanks.

**Comment by rameshnatesan** [comment]
Thank you very much! I will try it out.

-Ramesh

**Comment by rameshnatesan** [comment]
it worked fine in JDK 1.8!! Thank you for the fix.

**Comment by ntung** [comment]
@rameshnatesan How did you manage it working in JDK 1.8? Could you share me a bit of your experience please? I am struggling to make it done in Grails 2.5.5.
