### ISSUE TITLE
Couldn't configure spock-reports in grails 2.5.0 (was Configuring spock-reports from GebConfig)

### ISSUE THREAD

**Issue by alexboly** [renatoathaydes/spock-reports#45]
Shouldn't it be possible to configure spock-reports from GebConfig instead of using the META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties file?

**Comment by renatoathaydes** [comment]
I am not familiar with GebConfig and I don't expect all users of Spock and spock-reports to be using Geb. Can you expand on what you're asking?

**Comment by alexboly** [comment]
Thanks for your answer. And sorry, you're right and this is not really an issue for spock-reports. I was so wrapped in my problem that I wrote this without making sure it fits.

My problem is actually that I cannot configure spock-reports in grails. Here's what happened (quote from comment at issue https://github.com/renatoathaydes/spock-reports/issues/17)

"It doesn't work for me. I tried putting the .properties file with its path META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties in:

* grails-app/config/
* web-app/config/
* test/functional/

None of this works. The report is not created and there's no error reported.

I'm using grails 2.5.0."

**Comment by renatoathaydes** [comment]
No problem, let's close this issue and continue the discussion, with @rdmueller's help, in issue #17 .

**Comment by rdmueller** [comment]
so, to get started I tried to come up with a blog post which describes how to use the Spock-Reports with Grails3.0 together with a sample project:
https://rdmueller.github.io/Spock-Reports-with-Grails-3.0/

I will now try to craete the same for Grails 2.5

**Comment by rdmueller** [comment]
just finished the Grails 2.2.4 version:
https://rdmueller.github.io/Spock-Reports-with-Grails-2.2/

**Comment by renatoathaydes** [comment]
Thanks @rdmueller! that's really helpful! Since I'm not a  Grails user, I just wouldn't be able to write those! I think we should add links to these posts in the README, what do you think?

**Comment by rdmueller** [comment]
links would be nice, but I still need some evenings to brush these up.
Tomorrow, I'll assemble the example to Grails 2.5 - 
@alexboly: the trick seems to be to disable forked mode and then do the rest the same way as in my 2.2.4 example:

grails.project.fork = [
    test: false,
   [...]
]

I've also greate a SO question: http://stackoverflow.com/questions/31440381/forked-grails-vm-exited-with-error-while-running-test-app

**Comment by alexboly** [comment]
Cool! I am currently traveling so will be able to try it out next week.

**Comment by rdmueller** [comment]
ok. so here is the last blog post for Grails 2.5: https://rdmueller.github.io/Spock-Reports-with-Grails-2.5/

@renatoathaydes - feel free to link those posts :-)

**Comment by alexboly** [comment]
@rdmueller Thanks a lot for the instructions. I've successfully integrated spock-reports in my application with default templates. I will also try out custom templates in the future.

@renatoathaydes Thanks a lot for your support and for creating this plugin. If I can help in any way, please let me know.
