### ISSUE TITLE
Support for Spock Documentation Annotations

### ISSUE THREAD

**Issue by pheath** [renatoathaydes/spock-reports#46]
I'm not sure if this is possible, but it would be nice if the reports could pull in information from Spock's documentation annotations e.g. @Narrative, @Title, @Subject, etc.

**Comment by renatoathaydes** [comment]
This feature will be in the next version of spock-reports! We had discussed some of it already in https://github.com/renatoathaydes/spock-reports/issues/37 and I will get to it as soon as I finish working on a more hairy issue (parallel builds).

**Comment by renatoathaydes** [comment]
`@Narrative` and `@Title` are already available in branch `issue-39`.

**Comment by renatoathaydes** [comment]
`@Narrative`, `@Title` and `@Issue` are all available in release 1.2.6. More to come...

**Comment by pheath** [comment]
Awesome!  Thanks!

**Comment by pheath** [comment]
Do I have to do something specific to make the new fields show up in the report?

**Comment by renatoathaydes** [comment]
No, it should just work. The [sample report](http://codepen.io/renatoathaydes/full/ihGgt) shows what it looks like (and is used in the tests.

**Comment by renatoathaydes** [comment]
How embarassing. Just realized only `@Issue` made it into this release :(

The others were implemented in templates only!! Will add these annotations and more and have to make a new release! Damn.

**Comment by pheath** [comment]
OK.  I'm just glad to know that I'm losing my mind. ;-)

**Comment by renatoathaydes** [comment]
Alright, now it should be all in 1.2.7 which I just released. Please confirm and close this issue if it works now :)

**Comment by pheath** [comment]
It's working!  Yay!  Thanks for making it happen.
