### ISSUE TITLE
Spock annotation @Issue should only be a link if an actual link is used as value

### ISSUE THREAD

**Issue by kkapelon** [renatoathaydes/spock-reports#49]
At the moment the @Issue annotation appears always in the report as a link. This means that if the user annotates a Spock test with @Issue("JIRA-4569") the resulting report will contain a broken link.

A possible solution would be to create a link only if the value starts with http. Otherwise the report should render the annotation as simple text.

**Comment by renatoathaydes** [comment]
Yes, will fix this for the next release... for now, maybe you can just add the full link to the JIRA issue?
