### ISSUE TITLE
can we write to the report from the specification code ?

### ISSUE THREAD

**Issue by djocal** [renatoathaydes/spock-reports#55]
Hi renato and all spock-reports lovers, 

in order to generate even more documentation starting from spock specifications code, we'd like to write "dynamic strings" to the report; string literals next to BDD keywords are not enough in our case. Can we already do that, through which API or coding convention, please ?  If not, do you have any recommendation for contributing to it ?
(such feature exist in tools like Cucumber or Gauge)

At first, people are typically thinking at expressions for documentation strings:
    expect: "all following rules should be followed: ${resultFromSomeStaticCode()}"
(but we assume spock is not able to detect that it's documentation instead of code)

Thank you for any hints.

Nota bene: we're doing grails specifications, sometimes depending on `@TestFor` instrumentation, which is lately activated in the spec life cycle; for this reason, `@Unroll` + `where:` variables + `#variable` templating in doc string literals seems not working in certain cases.

**Comment by renatoathaydes** [comment]
Hi @djocal  sorry for the delay to answer...

I don't think it's possible to achieve this with spock-reports alone... I would think that Spock itself would need to support this first.

However, because of the dynamic features of Groovy, it may be possible to implement some hook in the report generator code which can be provided by your specification to add extra information to the report. Can you give me a realistic example of a situation where Spock String interpolation will not work and that would be useful to you?

Regards.

**Comment by djocal** [comment]
Hi Renato, even more sorry for the even bigger delay, here is a spec:
```groovy
@Stepwise
class WritingInTheReportSpec extends Specification {
    String aFunction() {
        return "a function result"
    }

    def "spock capture string literals, and spock-reports write them in the report"() {
        expect: "this text is written in the report"
        4 == 2 + 2
    }

    def "spock do not capture a function result because considered part of the specification"() {
        expect: "this expression with ${aFunction()} does not appear in the report" // when you reformat the code with intellij => this goes to the line.
        6 == 3 + 3
    }

    @Unroll
    def "a Workaround is to put the function result in a where variable, and include the variable in string literal the spock way, with Unroll"() {
        expect: "here we retrieve #result and it appears in the report"
        8 == 4 + 4
        where:
        result      || _
        aFunction() || _
    }
}
```
We think an helper function in order to make work the second test here, without the workaround indicated in the third one. 
Thank you for your opinion.

**Comment by renatoathaydes** [comment]
This should be a feature request to the spockframework project... I could make the html report resolve this string, but anywhere else you would see the unresolved String. Not as good as if Spock supported this.

**Comment by kovax** [comment]
I am looking for the same functionality.

@djocal It would be great to know if you have requested this feature from spockframework

**Comment by renatoathaydes** [comment]
Hope you guys saw that now it's possible to write to the reports from any Specification by just using the `reportHeader` and `reportInfo` methods, see the README for details.
