### ISSUE TITLE
Can not generate reports

### ISSUE THREAD

**Issue by saisurakanti** [renatoathaydes/spock-reports#56]
My project is build with Maven,

I have configured the properties file in META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties relative to my class path under src/test/resources

I have taken same sample file content and placed in that properties file.
but it is not generating any reports

am I missing something?

**Comment by saisurakanti** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6713700/12812040/3f13ce7c-cb28-11e5-9971-9723bdc324e3.png)

**Comment by saisurakanti** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6713700/12812105/b88f40ba-cb28-11e5-9db5-da12ab1c2b57.png)

**Comment by renatoathaydes** [comment]
You don't need to add any files anywhere, just add a dependency on spock-reports and Spock will automatically find spock-reports (in other words, add spock-reports to your test classpath).

The location you added the properties file seems correct. If Spock reports can use Java's `MyClass.class.getResource("/META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties")` then it will be found. You can try this to make sure it's in the correct location.

As the documentation says, if you use Grails, you need to read the specific instructions linked from the README page.

**Comment by brandami** [comment]
Hello saisurakanti, 

i had the same issue as you. Updating the spock-core version from 0.7-groovy-2.0 to 1.0-groovy-2.4 fixed the problem and the spock-reports extension is working now.

Hope this helps!
