### ISSUE TITLE
Test fail on windows

### ISSUE THREAD

**Issue by rdmueller** [renatoathaydes/spock-reports#61]
ProblemBlockWriterSpec and TemplateReportCreatorSpec fail because of line endings.

**Comment by renatoathaydes** [comment]
I'm not sure I have this problem because I get Git to change [line-endings](https://help.github.com/articles/dealing-with-line-endings/) automatically... do you have this option enabled? If so, Git should change the file endings to your OS's and maybe this problem wouldn't happen... I'm not sure if that makes a difference, but you can try that.

**Comment by rdmueller** [comment]
Sure, I will give it a try. Just thought that people shouldn't run into problems with the tests...

**Comment by renatoathaydes** [comment]
Sure, but it is impossible to not run into trouble if you don't manage whitespaces automatically.

**Comment by rdmueller** [comment]
So, what I see from my settings and the Git documentation is that the default for windows is that Git handles the line endings the way it thinks it is best :-) So I guess most windows users will run into the same problem as I did.

And as I understand the tests, only one of them depends on the Git settings - the other one fails because the stacktrace is created with different crlf than expected by the system.

But it's up to you how you want to handle this. Feel free to close this issue and the pull request.

**Comment by renatoathaydes** [comment]
@rdmueller thanks for checking what's happening. It's hard for me to test in different operating systems... but I think I will setup Travis CI to do that, so it becomes easier to fix this kind of issue.

I will accept your PR as soon as I make sure it still works for me on Linux and Mac :)

**Comment by rdmueller** [comment]
Hm. Setting up travis would be a great idea! This way test would automatically run before each PR...

Btw: I've already tested my changes also on linux...

**Comment by renatoathaydes** [comment]
https://travis-ci.org/renatoathaydes/spock-reports/builds/125665650 passing on Travis... merged!
