### ISSUE TITLE
Include version of software under test in reports

### ISSUE THREAD

**Issue by noxpert** [renatoathaydes/spock-reports#78]
It would be great to have included in the reports the version of the software under test from maven or gradle.

**Comment by renatoathaydes** [comment]
Sounds like a good idea!

**Comment by noxpert** [comment]
Thanks, let me know if there is something I can do to help with this.

**Comment by renatoathaydes** [comment]
This is released in version 1.3.0.

**Comment by noxpert** [comment]
Thank you. This is great.

**Comment by nartz** [comment]
What would be the recommended way to do this programatically? The main issue is that the version may be stored in multiple places - it would be great if we could just store it in one place. Would the recommended way be to just programatically generate the properties file?

**Comment by renatoathaydes** [comment]
In Gradle, add this to your build file:

```groovy

test {
    systemProperty 'com.athaydes.spockframework.report.projectName', project.name
    systemProperty 'com.athaydes.spockframework.report.projectVersion', project.version
}
```

If using Maven, set the system properties in the Maven pom:

```xml
<plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.5</version>
        <configuration>
          <systemPropertyVariables>
            <com.athaydes.spockframework.report.projectName>
                ${project.name}
            </com.athaydes.spockframework.report.projectName>
            <com.athaydes.spockframework.report.projectVersion>
                ${project.version}
            </com.athaydes.spockframework.report.projectVersion>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
```

**Comment by nartz** [comment]
This code doesn't seem to be working for me. I've tried just hardcoding the values inside of the projectName and projectVersion fields as well, but no dice - anything I may be missing? Is there a recommended/easier way to debug this?

**Comment by renatoathaydes** [comment]
The Gradle or Maven way?
