### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SevilRoach** [renatoathaydes/spock-reports#80]
What kind of license does this extension have?

**Comment by renatoathaydes** [comment]
https://github.com/renatoathaydes/spock-reports/blob/master/build.gradle#L83

**Comment by SevilRoach** [comment]
Thank you!

**Comment by david-w-millar** [comment]
A LICENSE or COPYING file in the root of the repository might be more explicit, play better with automated tools, and be more clear to folks that are not familiar with gradle or maven.

EG: Github examines LICENSE or COPYING file in the root of a repository to store meta-data about licensing and display it on the main project page.

**Comment by renatoathaydes** [comment]
Added LICENSE.txt to root folder.

**Comment by david-w-millar** [comment]
Thanks! Github is already showing the license on the main project page :)
