### ISSUE TITLE
Return more data on the blocks

### ISSUE THREAD

**Issue by johnok** [renatoathaydes/spock-reports#84]
At the moment we can get block.kind and block.text in the reports.
Would it be much extra work to get whether that block was the failure point. something like block.status?

This could be a good feature/addition going forward

**Comment by renatoathaydes** [comment]
Spock gives the line at which the test fails, but there's no way that I can see to find out which block was executing at that line.

To get the line where the test failed:

```groovy
// check first that exception has this type
def line = (errorInfo.exception as ConditionNotSatisfiedError).condition.position.line
```

This is the best I could come with...

**Comment by renatoathaydes** [comment]
In version 1.3.0, we released vivid reports which include the source code of the specification. Hence, we have access to which line of which block caused the error, as long as we know the line where the error came from (and assuming vivid reports are enabled). So, we could easily implement this  for the next release!

**Comment by renatoathaydes** [comment]
And that was done in release 1.3.2!

Please try vivid reports as they now show the line of code and block where the failure occurred.
