### ISSUE TITLE
Data Tables

### ISSUE THREAD

**Issue by davidmoshal** [renatoathaydes/spock-reports#87]
Hi, am curious: does spock-reports support datatables?
So far I've not been able to get this to work.

Thanks

**Comment by renatoathaydes** [comment]
Yes, it certainly does. Are you having any specific errors?

**Comment by davidmoshal** [comment]
wow, that IS a record response.
actually I was going to post the answer here, which is that the various methods:
`given`, `expect`, `where`, can all accept parameters, just like `@Unroll`.
 
That's something I didn't know was possible in Spock, but didn't take too long to figure out.

Thanks for the excellent project.

David

**Comment by renatoathaydes** [comment]
No problem, hope you enjoy it.

**Comment by davidmoshal** [comment]
e.g:

```groovy

given:
"input #a"
     .....

expect:
"result to equal #c"
    ....
    
where:
"b is #b"

    a | b | c | 
    4     | 3     | 7      
    etc.

```

**Comment by davidmoshal** [comment]
it's great!
a bit of documentation and examples could be helpful.
for example, took a while to realize that simply adding the jar is all you need to do (assuming non-Gradle), that's it, nothing else if you don't need to customize.

Thanks again.

**Comment by renatoathaydes** [comment]
Yeah, you're right, I will try to make that more clear!
