### ISSUE TITLE
Document Groovy modules dependencies

### ISSUE THREAD

**Issue by ddimtirov** [renatoathaydes/spock-reports#91]
For people not using the `groovy-all` artifacts it would be useful to know that the required Groovy deps are `groovy`, `groovy-xml` and `groovy-json`. 

If any of these is missing a not very helpful exception is logged and reports are not generated.

**Comment by renatoathaydes** [comment]
Thanks for reporting this. The plugin assumes `groovy-all` currently, you're right. I will fix for the next release. Will probably have to keep it as optional dependencies though, because otherwise you will endup with `groovy-all` + the other libs in your classpath.

**Comment by ddimtirov** [comment]
IMHO just documenting it would be enough.

**Comment by renatoathaydes** [comment]
Using only the correct libs in my classpath will avoid me making mistakes in the future and documenting the wrong setup.

**Comment by renatoathaydes** [comment]
Fixed dependencies and documented... released in version 1.3.0.
