### ISSUE TITLE
Add an option to disable the spock report creation

### ISSUE THREAD

**Issue by ddimtirov** [renatoathaydes/spock-reports#92]
I would like that only the Gradle builds produce spock reports (as when I run my Spock tests, the current dir tends to vary).

To that end have set the `com.athaydes.spockframework.report.IReportCreator` to empty string, so the `reportCreator` is not instantiated. Technically it works...

There is one annoyance though - when the tests finish I see these ugly warnings:

```
[main] WARN com.athaydes.spockframework.report.SpockReportExtension - Not creating report for FunctionsSpec as reportCreator is null
```

See also [here](https://github.com/renatoathaydes/spock-reports/blob/master/src/main/groovy/com/athaydes/spockframework/report/SpockReportExtension.groovy#L60)

Can we have a way to disable the report creation without warning please?

Right now I could implement myself a `NullReportCreator` but I would prefer not to.

**Comment by renatoathaydes** [comment]
Sure, that'd be easy to do with a system property, for example. Or you have another suggestion?

**Comment by renatoathaydes** [comment]
Done in version 1.3.0.
