### ISSUE TITLE
Please update summary-template.md

### ISSUE THREAD

**Issue by rameshnatesan** [renatoathaydes/spock-reports#94]
I am using custom report since spock-reports:1.2.7. When I used spock-reports:1.2.13, for some reason the summary-template.md is not valid and it is not creating summary file. It is creating only the spec files.
I think there is something to look into this line. Is this using data or aggregatedData ?
```
def stats = com.athaydes.spockframework.report.util.Utils.aggregateStats( data )
```

**Comment by renatoathaydes** [comment]
The format of the data changed a little bit.

Previously, `data` had the form:

```json
{
  "spec": { "failures": 0, "errors": 0, "time": 1 },
  ...
}
```

This was changed to:

```json
{
  "spec": {
    "stats": { "failures": 0, "errors": 0, "time": 1 },
     ...
  }
}
```

That allowed me to add more information to the `data` (which is saved in a JSON file for external tools and for housekeeping on multi-threaded builds).

Sorry for the inconvenience, but it should be easy to  fix in your template, just replace `item.failure` to `item.stats.failure` (where item is each value in the json as shown above).
