### ISSUE TITLE
Show code for blocks without description

### ISSUE THREAD

**Issue by hexmind** [renatoathaydes/spock-reports#96]
Currently, empty blocks are shown like this:
`Where: ----`

Groovy tests should be written meaningful and often it doesn't make sense to describe each block (duplication or comment out of date):
```
def "should add numbers"() {
        expect: "sum of 2 and 2 is 4"
            2 + 2 == 4
}
```
What do you think about to generate block description from code (with Groovy ASTTransformation):
```
when: "send \"hello\""
    publisher.send("hello")
then:
    2 * subscriber.receive("hello")
```
can be in report:
```
When:  send "hello"
Then: 2 times subscriber receive "hello"
```
It could be experimental feature enabled by annotation.
In MVP only code when no block description provided (without human-readable transformation like in example).

**Comment by renatoathaydes** [comment]
That could be nice. Are you able to make a minimal implementation of that? I can help if you get it started.

If you make a PR, please target the `next` branch.

**Comment by hexmind** [comment]
I can't promise when but yes, I will try to do it.

**Comment by hexmind** [comment]
I have a code draft that works like below.
```
package com.athaydes.spockframework.report

import spock.lang.Issue
import spock.lang.Narrative
import spock.lang.See
import spock.lang.Specification
import spock.lang.Unroll

/**
 *
 * User: Renato
 */
@Narrative("""
As a user
I want foo
So that bar""")
class VividFakeTest extends Specification {

    def "A first test with Then code block"() {
        given:
            "we have x and y"

        and:
            "some more things"

        when:
            "I do crazy things"

        then:
            x == y

        where:
            "The examples below are used"
            x | y
            'a' | 'a'
            'b' | 'c'
    }

    def "Another feature without code"() {
        setup:
        "Setup block here"
        expect:
        "Expecting something ??"
    }

    def "Another feature with method call"() {
        expect:
        add(1, 2) == 3
    }

    private static int add(int a, int b) {
        return a + b
    }

    @Issue( [ "http://myhost.com/issues/995", "http://myhost.com/issues/973" ] )
    def "A test with an error"() {
        when:
        "An Exception is thrown"
        throw new RuntimeException( 'As expected' )

        then:
        "Will never succeed"
    }

    @See( "http://myhost.com/features/feature-234" )
    def "A test with a failure"() {
        when:
        "Do nothing"
        then:
        "Test fails"
        assert 3 == 2
    }

    def "A Spec without block Strings"() {
        given:
        int a = 0

        and:
        int b = 1

        when:
        int c = a + b

        then:
        c == 1

        and:
        c > 0
    }

    @Unroll
    def "An @Unrolled spec with x=#x and y=#y"() {
        setup:
        "nothing"
        expect:
        x == 0
        and:
        "An error if y is 5"
        if ( y == 5 ) throw new RuntimeException( 'y is 5' )
        where:
        x | y
        0 | 1
        2 | 3
        0 | 5
    }

}
```



```
# Report for com.athaydes.spockframework.report.VividFakeTest

##Summary

* Total Runs: 9
* Success Rate: 44.44%
* Failures: 3
* Errors:   2
* Skipped:  0
* Total time: Unknown

###As a user
###I want foo
###So that bar


## Features

### A first test with Then code block

Result: **FAIL**

* Given: we have x and y

* And: some more things

* When: I do crazy things

* Then: x == y

* Where: The examples below are used

 | x | y |
 |---|---|
 | a | a | (PASS)
 | b | c | (FAIL)

The following problems occurred:

* [b, c]
```
Condition not satisfied:

x == y
| |  |
b |  c
  false
  1 difference (0% similarity)
  (b)
  (c)

```

### Another feature without code

Result: **PASS**

* Given: Setup block here

* Expect: Expecting something ??

### Another feature with method call

Result: **PASS**

* Expect: add(1, 2) == 3

### A test with an error

#### Issues:

* http://myhost.com/issues/995
* http://myhost.com/issues/973

Result: **ERROR**

* When: An Exception is thrown

* Then: Will never succeed

The following problems occurred:

```
java.lang.RuntimeException: As expected
```

### A test with a failure

#### See:

* http://myhost.com/features/feature-234

Result: **FAIL**

* When: Do nothing

* Then: Test fails

The following problems occurred:

```
Condition not satisfied:

3 == 2
  |
  false

```

### A Spec without block Strings

Result: **PASS**

* Given: int a = 0

* And: int b = 1

* When: int c = a + b

* Then: c == 1

* And: c > 0

### An @Unrolled spec with x=0 and y=1

Result: **PASS**

* Given: nothing

* Expect: x == 0

* And: An error if y is 5

* Where: ----

 | x | y |
 |---|---|
 | 0 | 1 | (PASS)

### An @Unrolled spec with x=2 and y=3

Result: **FAILURE**

* Given: nothing

* Expect: x == 0

* And: An error if y is 5

* Where: ----

 | x | y |
 |---|---|
 | 2 | 3 | (FAIL)

The following problems occurred:

* [2, 3]
```
Condition not satisfied:

x == 0
| |
2 false

```

### An @Unrolled spec with x=0 and y=5

Result: **ERROR**

* Given: nothing

* Expect: x == 0

* And: An error if y is 5

* Where: ----

 | x | y |
 |---|---|
 | 0 | 5 | (FAIL)

The following problems occurred:

* [0, 5]
```
java.lang.RuntimeException: y is 5
```


<small>Generated by <a href="https://github.com/renatoathaydes/spock-reports">Athaydes Spock Reports</a></small>
```

**Comment by renatoathaydes** [comment]
It looks good. Do you think this is reliable (will work with any code in the blocks)? Are you planning to make a pull request soon?

**Comment by hexmind** [comment]
I am working on PR and it should be reliable.
It will be triggered by com.athaydes.spockframework.report.showCodeBlocks=true property.

**Comment by renatoathaydes** [comment]
I think you can make this property default to true. I can't think of a reason why people would prefer to see `---` rather than a little code (hopefully people don't write specs that have hundreds of lines of code per block :D ).

**Comment by hexmind** [comment]
Eventually yes. But remember, currently we should think about this feature like about experimental one. It wasn't tested on too many specifications classes.

**Comment by renatoathaydes** [comment]
why not? Just add tests... I can add more later.

**Comment by renatoathaydes** [comment]
@hexmind I've been trying to fix the code you submitted for a week now, and I am nowhere near finishing. I had thought you had implemented something that at least would work for simple cases, but it doesn't even work for the simplest of cases at all.

Only one line of code is captured, and only if the line happens to be a simple case where the first statement is not a constant or any expression other than `ExpressionStatement`.

FYI you did not handle the following other cases:

<img width="519" alt="screen shot 2017-03-30 at 21 23 56" src="https://cloud.githubusercontent.com/assets/1901277/24522290/66f1bfbe-158f-11e7-98d8-4326a2155d4e.png">

The mapping between code lines and blocks would only work if the spec had a single block definition for each keyword (ie. only one `given`, `when` and `then`). Nevermind most specifications repeat blocks, sometimes several times...

Unfortunately, the code has been merged to next, which already contained quite a few other changes for the next release...

My question is: do you have time to help finish implementing this feature correctly?

I know how to do it, but I don't have all the time in the world to spend on this! So any help would be appreciated, I can tell you what needs to be done. Let me know.

**Comment by rdmueller** [comment]
This feature is great and I would like to see it implemented!

**Comment by renatoathaydes** [comment]
@rdmueller thanks for letting me know :) I need quite a lot of motivation to keep working on it!

**Comment by rdmueller** [comment]
that's why I keep telling you :-)

I have the feeling that the groovyConsole with the included AST browser (Strg+T) might contain the solution. Isn't it open source?

**Comment by renatoathaydes** [comment]
I know how to do it the hard way, which is by handling every single statement type (shown in the image I posted). Would be awesome to let some library do it for us, though... Spock itself captures only single expressions, it seems, not the full source for a block... that's why it's hard, because we need to iterate through each statement, figure out how to handle each type, then ask the Spock's `org.spockframework.compiler.SourceLookup#lookup` method for the source code of the statement. See my latest commit where I started doing it.

**Comment by renatoathaydes** [comment]
This feature is now implemented correctly! I found out that Spock's source code lookup works for any AST node, no need to recurse into each expression, so it's much easier and much more reliable.

I had to change completely the implementation, but that was mostly refactoring and cleaning up, the hard part is done by Spock (to actually read the source code from each class).

I will still add more tests for the lots of edge cases (nested classes, several classes in one file, specs with methods that look like tests but are not, etc).

Soon we can have this released.

**Comment by renatoathaydes** [comment]
BTW. Please checkout the "next" branch and take this code for a spin!

Add this to your `META-INF/services/com.athaydes.spockframework.report.IReportCreator.properties` file and run your tests:

```
com.athaydes.spockframework.report.IReportCreator=com.athaydes.spockframework.report.template.TemplateReportCreator

# Set properties of the report creator
com.athaydes.spockframework.report.template.TemplateReportCreator.showCodeBlocks=true
```

Let me know if you have issues.

**Comment by hexmind** [comment]
Hi @renatoathaydes  and sorry for delayed response. I see that you did it. 
Can I finish with HtmlReportCreator?

**Comment by renatoathaydes** [comment]
@hexmind you can submit a PR, of course, if you want to help.

**Comment by renatoathaydes** [comment]
Done in version 1.3.0.
